### ISSUE TITLE
Immutable ArrayView<'a, A, D> shoud probably implement `Clone`.

### ISSUE THREAD

**Issue by rustonaut** [rust-ndarray/ndarray#1010]
As far as I understand it `ArrayView<'a, A, D>` is basically a "fancy"/"complex" reference to an array (or a subset of it, and yes it's not trivial).

You can always create multiple identical `ArrayView`'s with the same lifetime, data etc. from the same `Array`.

But you can't duplicate a array view (1).

E.g. if I have a `&'short &'long [A]` I always can get the `&'long [A]` out because of `&` being Copy and the
lifetime being guaranteed to be `'long`.

But I can't do the same with a `&'short ArrayView<'long, A, D>`...

I have run into that limitation twice already in a relatively short time of using `ndarray`.

So I think it would be grate if `ArrayView<'long, A, D>` could implement `Clone`.

Or do I miss something?

(1): At least not with the same lifetime, a always can create a `ArrayView<'short, A, D>` from a `&'short ArrayView<'long, A, D>`, but I need another `ArrayView<'long, A, D>`.

**Comment by jturner314** [comment]
`ArrayView` does implement `Clone` (and even `Copy` if the dimension type is `Copy`). Will you please provide some example code to illustrate the issue you're experiencing? Maybe you're trying to clone a generic `ArrayView<A, D>` and are missing a `D: Clone` bound?

**Comment by rustonaut** [comment]
Thanks, how embaressing :facepalm:, I got tricked by how rustdoc does (and doesn't) list trait implementations for type aliases...

And the problem is actually less the `Clone` but more most other operations.

E.g. we can have 

```rust
fn short_long<'s,'l: 's>(v: &'s &'l [u8]) -> &'l [u8] {
    &v[1..]
}
```

But cant do:

```rust

fn short_long2<'s,'l: 's>(v: &'s ArrayView2<'l, usize>) -> ArrayView2<'l, usize> {
    v.slice(s![-1.., ..])
}
```

Through there is not  much which can be done as I guess as you would need to implement alternate versions of to many methods, including `slice` and the various subview iterators. Which also would conflict in name :disappointed: 

Or did I overlook something?
