### ISSUE TITLE
Efficiently map array to a (possibly) different type

### ISSUE THREAD

**Issue by benkay86** [rust-ndarray/ndarray#1031]
[`ArrayBase::mapv_into()`](https://docs.rs/ndarray/0.15.3/ndarray/struct.ArrayBase.html#method.mapv_into) consumes self and reuses its memory allocation to compute a new array with the same shape and type.  Avoiding unnecessary allocations is important when mapping very large arrays.

When writing generic methods, it is often necessary to assume that two arrays may be of different types even though we might expect them to be the same type most of the time.  For example, a method that is generic over complex numbers may be called with all real arguments, all complex arguments, or a mixture of real and complex arguments.  This precludes direct use of `mapv_into()` since we cannot assume the arguments are the same type.

Would it be worth adding something like this [`trans_mapv_into()`](https://gist.github.com/benkay86/b9f3eea271999eccf158bfbbcd30b70e), which maps an array with elements of one type to a (possibly) different type?  If the types are the same it delegates to `mapv_into()`, and if the types are different it falls back to using additional allocations.  Type comparison is performed at runtime pending [specialization](https://github.com/rust-lang/rust/issues/31844).

**Comment by bluss** [comment]
So for this use case, the element type is something with non-trivial Clone or not? Or is it just a Copy element type?

**Comment by benkay86** [comment]
For my use case `trans_mapv_into()` is meant to be a drop-in replacement for `mapv_into()` with possibly worse performance if the types are different.  The trait bounds are as close as possible to `mapv_into()`, which means the mapped type is `Clone` just like in `mapv_into()`:

```rust
pub fn mapv_into<F>(mut self, f: F) -> Self
    where
        S: DataMut,
        F: FnMut(A) -> A,
        A: Clone,
        // ...
```

**Comment by benkay86** [comment]
@bluss, it's been a few days, so just checking again to see if [`trans_mapv_into()`](https://gist.github.com/benkay86/b9f3eea271999eccf158bfbbcd30b70e) or something like it fits into your vision of what ndarray should offer.  If so, I would welcome feedback on what the interface (e.g. `Clone` vs `Copy`) and implementation (whether to use `unsafe` or rely on the optimizer for efficient downcasting) should look like prior to opening a pull request.

If this just isn't a fit that's totally fine by me!  I can focus on integrating this functionality into my own code or a separate, helper crate.

**Comment by bluss** [comment]
I'm not currently working on ndarray, so days are currently a too short time scale :slightly_smiling_face: . Last months I did a lot of work on it. The idea makes sense, but I'd probably tweak the signature and name if I had a go at it. About your current implementation I must point out that `into_raw_vec` is hard to use correctly, and it has an error even here (for arrays that are sliced in place).

**Comment by benkay86** [comment]
@bluss, fair enough!  As the most active committer I thought maybe you were the official maintainer of ndarray 😅.  I guess I'll turn this into a pull request and solicit feedback that way.

I'm not sure that I see the error in `into_raw_vec()` -- I thought it was always safe to use if the array is in standard memory layout?  But I am definitely rejoicing the introduction of `into_iter()`!

**Comment by bluss** [comment]
Well you're not wrong, I wrote most of ndarray and am one of the maintainers
