### ISSUE TITLE
Use intra-doc links

### ISSUE THREAD

**Issue by LeSeulArtichaut** [rust-ndarray/ndarray#1032]
[Intra-doc links are now stable since 1.48.0 :tada:](https://blog.rust-lang.org/2020/11/19/Rust-1.48.html#easier-linking-in-rustdoc) Using them would simplify docs.
cc #558

**Comment by LeSeulArtichaut** [comment]
(I can work on implementing this)

**Comment by bluss** [comment]
Contributions are welcome. We use doc links in some places already.
