### ISSUE TITLE
Why can Arrays not contain custom types?

### ISSUE THREAD

**Issue by Wuelle** [rust-ndarray/ndarray#1034]
I wonder why it's not possible to put a struct defined in my crate into an ArrayBase to get something like `Array3<MyCustomStruct>`. (Since `RawData` cannot be implemented)

**For Context:**
I am working with [dual Numbers](https://en.wikipedia.org/wiki/Dual_number) which, like complex numbers, basically consist of two real numbers. So as long as i implement traits like `std::ops::Add` and `std::marker::Sized` it should be possible to just use it like an `f32` - right?

**Comment by bluss** [comment]
They can, there is no such limit. Start with Array::from_vec and see.
