### ISSUE TITLE
Modifying array row in place

### ISSUE THREAD

**Issue by curldivergence** [rust-ndarray/ndarray#1045]
Hello. I'm sure I'm missing something pretty simple, so sorry in advance for the silly question :) But unfortunately I cannot figure out how to AddAssign to a row of an array.
As I understand from the docs, I cannot index an Array2 like a usual Rust 2D array (i.e. operator[] won't give me a row), but instead I need to get a mutable view to the row via row_mut():
```
let mut triangle = Array2::zeros((3, 3));
for vtx_idx in 0..3usize {
    triangle.row_mut(vtx_idx) += &arr1(&[1., 2., 3.]);
}
```
But unfortunately, this bit of code won't compile due to an error that says that the expression on the left hand side cannot be assigned to. So could you help me with this, please? :)
Thanks!

**Comment by jturner314** [comment]
Not all expressions can be used on the left side of an assignment; only "place expressions" are allowed. See [the Rust reference](https://doc.rust-lang.org/reference/expressions.html#place-expressions-and-value-expressions) for details. Here are a couple of options:

```rust
use ndarray::prelude::*;
use std::ops::AddAssign;

fn main() {
    let mut a: Array2<u8> = array![[0, 0, 0], [0, 0, 0]];
    let b = array![1, 1, 1];
    
    // Doesn't work: invalid left-hand side of assignment.
    // a.row_mut(0) += &b;
    
    // Make the left side into a place expression.
    *&mut a.row_mut(0) += &b;
    assert_eq!(a, array![[1, 1, 1], [0, 0, 0]]);
    
    // Import the `AddAssign` trait (see the top of the example)
    // so that you can call `.add_assign()`.
    a.row_mut(0).add_assign(&b);
    assert_eq!(a, array![[2, 2, 2], [0, 0, 0]]);
}
```

([Playground](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=b5b1748db3b2922d51f3490677358a1e))

**Comment by curldivergence** [comment]
@jturner314, I see, thank you very much for help :)
