### ISSUE TITLE
Implement `powi` and `powf` for `ArrayBase`

### ISSUE THREAD

**Issue by multimeric** [rust-ndarray/ndarray#1047]
Currently `a ** 3` is the only example in the "[ndarray_for_numpy_users](https://docs.rs/ndarray/0.15.3/ndarray/doc/ndarray_for_numpy_users/index.html)" docs that requires a map. Could these methods be added directly? Rust has no `^` or `**` exponentiation operator, but these two methods are implemented on numeric primitives, and I see no reason why they can't be added for arrays here for convenience.

**Comment by nilgoyette** [comment]
Done in https://github.com/rust-ndarray/ndarray/pull/1042
