### ISSUE TITLE
Possible race condition in par_for_each

### ISSUE THREAD

**Issue by frjnn** [rust-ndarray/ndarray#1052]
## The issue

Hello, 

I'm having trouble tracking a bug that seems to randomly appear in my repo. The relative issue is neuronika/neuronika#67.

## Some clues 

I believe it may be due to a race condition, as I can't seem to reproduce the error when using a sequential `for_each` and running the test several times (30+); in this case the tests pass. Do note that the oracle I used to get the correct results to test against is the pytorch library.

## The code

I'll try to sum up what the code linked in the issue does. I hereby report the function that causes the error.

```rust
/// Assigns to the **n**-dimensional feature map's gradient `dest` the **2**-dimensional
/// array `columns`. This method encapsulates the functionalities of **col2sig**, **col2im** and
/// **col2vol**.
///
/// **n** can be either 3, 4 or 5.
pub(super) fn assign_from_cols<D: Dimension, S: DataMut<Elem = f32>, T: Data<Elem = f32>>(
    dest: &mut ArrayBase<S, D>,
    columns: ArrayBase<T, Ix2>,
    kernel_shape: &[usize],
    stride: &[usize],
    dilation: &[usize],
) {
    let mut dest_windows_mut = as_windows_mut(dest, kernel_shape, stride, dilation);
    let from_cols = columns.into_shape(dest_windows_mut.raw_dim()).unwrap();

    Zip::from(&mut dest_windows_mut)
        .and(&from_cols)
        .par_for_each(|dest_el, src_el| *dest_el += *src_el);
}
```

The snippet is located [here](https://github.com/neuronika/neuronika/blob/7e6135bf14db4f839df8d153537f615da11add4f/src/variable/node/binary/convolution/numeric/mod.rs#L577).

## Further details

1. `as_windows_mut` gets a mutable rolling window view of the input map's gradient `dest`, it does so by using some *stride tricks*. It may be important to state that such resulting array is **not** in standard layout.
2.  After obtaining the rolling window view, the incoming gradient in column format, that is `columns`,  gets reshaped to match the rolling window mut of the input map's gradient. The number of elements in the two is the same.
3. At this point the `par_for_each` performs the actual assignment.

As stated above, replacing `par_for_each` with `for_each` seem to solve the issue.

**Comment by bluss** [comment]
Without further information, I would first suspect your unsafe code block here:

```rust
pub(super) fn as_windows_mut<'a, D: Dimension, S: DataMut<Elem = f32>>(
    input: &mut ArrayBase<S, D>,
    window_shape: &[usize],
    stride: &[usize],
    dilation: &[usize],
) -> ArrayViewMut<'a, f32, IxDyn> {
    let rolling_window_shape: Vec<usize> =
        compute_rolling_window_shape(input, window_shape, stride, dilation);
    let rolling_window_strides: Vec<usize> =
        compute_rolling_window_strides(input, stride, dilation);

    unsafe {
        ArrayViewMut::from_shape_ptr(
            rolling_window_shape.strides(rolling_window_strides),
            input.as_mut_ptr(),
        )
    }
}
```

Does this compile using debug assertions? Even if it does, that is not assurance that the code is correct. It's likely you're using stride tricks that break ndarray's model and that are incorrect.

I haven't read your code, but the comment says "Computes the shape of a rolling window view." which sounds incompatible with a mutable array view.

**Comment by frjnn** [comment]
> Does this compile using debug assertions?
Yes it does.

> One requirement that may need to be spelled out more clearly - strides must not result in elements that alias. I.e. it must not be possible to reach the same element through two different indexes.
Spot on, this is exactly what I was trying to achieve! And surely what's causing the error with parallelism...

I'll figure out something else. Thank you very much.

**Comment by bluss** [comment]
Good. We need to update the doc and possibly the debug assertion in the relevant function.

Take note that this is nog merely an incompatibility with parallelism, but ndarray considers that situation with aliasing in the mut array view broken in all contexts, also single threaded. Thanks.
