### ISSUE TITLE
Indexed lanes

### ISSUE THREAD

**Issue by zareami10** [rust-ndarray/ndarray#1066]
This could have quite a few usages. Such as having access to the pixel coordination when dealing with an RGB image in a 3 dimensional array, without extra code.

Although I am not sure about the best API as there is already a lot of confusing conventions around indexing and iterating, maybe implementing `indexed_iter` for Lanes instead of `indexed_lanes`?

**Comment by bluss** [comment]
The index is already available using `Zip::indexed(lane_producer)`, isn't this enough? The producers are generally better and much more performant than any iterators.

**Comment by zareami10** [comment]
> The index is already available using `Zip::indexed(lane_producer)`, is this enough? The producers are generally better and much more performant than any iterators.
> 
> It's not great, but the Iterator API causes some of this. If users would prefer to use indexed iterators instead of indexed Zip, then their code ends up slower unfortunately.

Thank you for your response. I just found out about Zip::indexed some time ago and was able to use it as intended, with the ability to easily run it in parallel. Although I should admit it took me a while to figure things out.

So although I'm not exactly sure about the API, the functionality is definitely there, so I'm closing this.
