### ISSUE TITLE
Add Array::from_shape_empty(shape)

### ISSUE THREAD

**Issue by HaoboGu** [rust-ndarray/ndarray#1069]
Hello,

I'm wondering if it's possible to add `Array::from_shape_empty(shape)`, just like `torch.empty` in PyTorch to create a ndarray with arbitrary data?

**Comment by bluss** [comment]
Hi, I think pytorch is just exposing uninitialized memory; like allocating something and using it without initialization. You can see this in numpy too, experiment a bit with `np.empty(100, dtype=np.uint32)` if you want, for example.

We would provide this in Rust if we could - but we can't according to the safety rules, access uninitialized values. We already provide `Array::uninit` as an access point and API for uninitalized arrays, and I believe that's about it. Without any new findings or Rust changes, I'd move towards closing this issue.

**Comment by HaoboGu** [comment]
Thanks, I'll try `uninit` in my project
