### ISSUE TITLE
IntoIterator and IndexedParallelIterator for Zip?

### ISSUE THREAD

**Issue by adamreichold** [rust-ndarray/ndarray#1077]
I have [a problem](https://github.com/GeoStat-Framework/GSTools-Core/pull/6) where I was unable to apply the methods provided by `Zip` and therefore decay that into a `Parallellterator` to be able to use arbitrary `fold` and `reduce` operations. Due to the large size of the temporary arrays, I would like to use Rayon's `with_min_len` to avoid the `Zip` being split too often (and thereby allocating too many temporary arrays). However, this method is only available on `IndexedParallelIterator` instances which `Zip` is not. This seems to be related to `Zip` also not implementing `IntoIterator` in contrast to over `NdProducers`.

Is there a fundamental issue which prevents providing those traits for `Zip` (After all, it does implement `SplitAt` and provides a `size` method.) or is this just not yet implemented?

**Comment by bluss** [comment]
I think it's a fundamental issue. The NdProducers that are more than one-dimensional don't implement IntoIterator or indexing, since they don't have an efficient correspondance with a one dimensional sequence.
