### ISSUE TITLE
Can we use it in ARM machines (mobile phones)?

### ISSUE THREAD

**Issue by fzyzcjy** [rust-ndarray/ndarray#1083]
Hi thanks for the lib! I wonder whether we can use it in ARM machines (mobile phones)? Will it be fast or not?

**Comment by ethanhs** [comment]
`ndarray` definitely works on ARM. Below you can see running the test suite on my phone using the Termux app.
<img width="378" alt="scrcpy_lIspUR96RL" src="https://user-images.githubusercontent.com/9504279/140648494-129e5d3a-e896-4562-83e5-b97578926d7c.png">

As for speed, it seems to at least run the tests reasonably quickly. For matrix multiplication and such, speed will likely depend on how well optimized for ARM `matrixmultiply` or the BLAS implementation you use. For example, openblas is optimized for a wide variety of architectures and I expect building with openblas (if it works) ndarray should perform reasonably well.

Of course, the processor in most phones is not as fast as that of a laptop/desktop/server.

**Comment by fzyzcjy** [comment]
Thanks!
