### ISSUE TITLE
ArrayD example for 7 or higher dimension

### ISSUE THREAD

**Issue by ungsik** [rust-ndarray/ndarray#1086]
I created an 8 dimension ArrayD.
I can not find how to index the ArrayD for 8 dim.
Compiler raises 
the trait `NdIndex<Dim<IxDynImpl>>` is not implemented for `[usize; 8]` error when addressing
array[[i, j, k, l, m, n, o, p]].
When tuple form is tried, 
the trait `NdIndex<Dim<IxDynImpl>>` is not implemented for `(usize, usize, usize, usize, usize, usize, usize, usize)` error is raised.

**Comment by ethanhs** [comment]
It looks like #980 will implement for `[usize; T]` using const generics, so in 0.16.x you should be able to use `array[[i, j, k, l, m, n, o, p]]`, and the compiler error you got should go away :)
