### ISSUE TITLE
How to stack/concatenate from vector of arrays?

### ISSUE THREAD

**Issue by zgbkdlm** [rust-ndarray/ndarray#1112]
Functions `stack` and `concatenate` can only stack arrays from array. Is it possible to stack a vector of ArrayView also?

For example, the snippet below fails to stack from a vector of Array.

```rust
extern crate ndaray;

use ndarray as na;

let a = na::arr2(&[[1., 2.], [3., 4.]]);

# Now create a vector of ArrayView
let vec_of_as: Vec<_> = vec!([a.view(), a.view()]);

# This will fail
let z = na::stack![Axis(0), &vec_of_as[..]].unwrap();

# This will work, of course.
let z = na::stack(Axis(0), &[a.view(), a.view()]).unwrap();
```

If this feature is not supported, I think it may be good to have it. For example, the parallel lib `rayon` usually gives a vector of elements from `.collect()`, and someone may want to do something in parallel and stack them together.

**Comment by bluss** [comment]
> `vec!([a.view(), a.view()]);`

you have a problem here, this is not a vec of arrayview, but a vec of array of arrayview. Should work with that fixed.
