### ISSUE TITLE
Documentation for ArrayBase::{nrows,ncols} use square matrix examples.

### ISSUE THREAD

**Issue by vi** [rust-ndarray/ndarray#1120]
It is easy to confuse width and height, or rows and columns when working with matrices.

Yet examples in ndarray's documetation often use square 2x2 matrices:

```rust
use ndarray::array;
let array = array![[1., 2.], [3., 4.]];
assert_eq!(array.nrows(), 2usize);
```

It is not immediately obvious whether it would be still `2` or change to `3` if `array![[1., 2.], [3., 4.], [5., 6.]];` were used instead.

**Comment by bluss** [comment]
Thanks, that's something that's easy to fix.

I'm thinking that when written multiline this it should be quite easy to see

```diff
+    /// use ndarray::{array, Axis};
+    ///
+    /// let array = array![[1., 2.],
+    ///                    [3., 4.],
+    ///                    [5., 6.]];
+    /// assert_eq!(array.nrows(), 3);
+    ///
+    /// // equivalent ways of getting the dimensions
+    /// // get nrows, ncols by using dim:
+    /// let (m, n) = array.dim();
+    /// assert_eq!(m, array.nrows());
+    /// // get length of any particular axis with .len_of()
+    /// assert_eq!(m, array.len_of(Axis(0)));
```

(and added some bonus references to .dim() and .len_of)
