### ISSUE TITLE
Document `astype` functionality in ndarray

### ISSUE THREAD

**Issue by sgasse** [rust-ndarray/ndarray#1124]
Hi! I took a stab at `Document ndarray's equivalent to NumPy's astype` from #597 in this PR:
https://github.com/rust-ndarray/ndarray/pull/1123

Here are a few questions:
- Which other conversion examples would you like to see?
- How can I locally build / access the `ndarray_for_numpy_users` documentation to see how my changes look like? I cannot find the page when running `cargo doc --open`.
- Should there be more details on differences in conversion that stem from Rust's type system and are not specific to `ndarray`? (e.g. `np.astype()` does not saturate, `a.mapv(|x| x as u8` runs a saturated conversion)

**Comment by adamreichold** [comment]
> How can I locally build / access the ndarray_for_numpy_users documentation to see how my changes look like? I cannot find the page when running cargo doc --open.

I think you just need to enable the `docs` feature, i.e. run
```sh
> cargo doc --features docs --open
```

**Comment by sgasse** [comment]
Thank you @adamreichold , that worked :pray:
