### ISSUE TITLE
Diagonal Does not Honor Transpose

### ISSUE THREAD

**Issue by ProgrammingIncluded** [rust-ndarray/ndarray#1144]
Hi all,

Slightly new to the library so apologies if I am missing a key part of the documentation here. Still trying to fully wrap my head around slicing vs. views. I stumbled upon this use-case as I was trying to get the other diagonal of a matrix e.g. indices `(n, 0), (n-1, 1)... (0, n)`.

## Reproduction

On `ndarray` version `0.15.4` using Windows 10.

It seems that `diag()` does not honor the `t()` function and returns the diagonal of the original array.:

```rust
use ndarray::{Array1, Array2, s};
let x = Array2::from(vec![[0, 1], [1, 0]]);

let a = x.diag();
// OK, contains: [0, 0], shape=[2], strides=[3], layout=Custom (0x0), const ndim=1
assert!(Array1::from(vec![0, 0]) == x.diag());

// Fails, contians: [0, 0], shape=[2], strides=[3], layout=Custom (0x0), const ndim=1
assert!(Array1::from(vec![1, 1]) == x.t().diag());
```

## Work Around

Using slices and reversing the axes before calling diagonal preserves honors `diag()`:

```rust
use ndarray::{Array1, Array2, s};
let x = Array2::from(vec![[0, 1], [1, 0]]);

// OK, contains: [1, 1], shape=[2], strides=[-1], layout=Custom (0x0), const ndim=1
assert!(Array1::from(vec![1, 1]) == x.slice(s![..; -1, ..; 1]).diag());
```

##  Concluding Thoughts

Would this be an intended design choice? As someone fairly new to the library, it seems a bit counterintuitive. Would appreciate any feedback, thanks.

**Comment by jturner314** [comment]
The diagonal of an array and the diagonal of its transpose are equivalent. [This illustration may help.](https://en.wikipedia.org/wiki/File:Matrix_transpose.gif)

Given this array (A):

```
0 1
2 3
```

the diagonal is `[0, 3]`. The transpose (A^T) flips the array over its diagonal, resulting in:

```
0 2
1 3
```

The diagonal is still `[0, 3]`.

As you discovered, to obtain the diagonal with the indices (n, 0), (n-1, 1), ... (0, n), you can invert axis 0, and the take the diagonal of that array. Inverting axis 0 of A results in:

```
2 3
0 1
```

which has diagonal `[2, 1]`.

**Comment by ProgrammingIncluded** [comment]
Got it. I don't know why... I totally derped. Thank you very much for taking the time to write!
