### ISSUE TITLE
ndarray of type non-numeric? Maybe ndarray of pointers?

### ISSUE THREAD

**Issue by ibarrond** [rust-ndarray/ndarray#1161]
It would be nice to create ndarrays of custom types, not only numerics.

My first thought would be to use ndarrays of pointers to such objects, but I have no clue how. 

The motivating example is simple: I have a vector/1D array of objects of custom type, but it actually represents a 2D array. To access all the elements in a row/column I am currently forced to do a for loop with carefully chosen iterators.

**Comment by adamreichold** [comment]
Why not store those values inside an `Array` directly without any indirection? Could you share some concrete code on what you want to achieve.

For example,

```rust
let array = array![["1x1".to_owned(), "1x2".to_owned()], ["2x1".to_owned(), "2x2".to_owned()]];
```

works and creates `Array<String, Ix1>`.

**Comment by adamreichold** [comment]
Similarly, 

``rust
let vec = vec!["1x1".to_owned(), "1x2".to_owned(), "2x1".to_owned(), "2x2".to_owned()];
let array = Array::from_vec(vec).into_shape((2,2));
```

takes a `Vec<String>` and turns it into an `Array<String, Ix2>`.

**Comment by ibarrond** [comment]
@adamreichold How would you, say, concatenate the strings per row? and per column?

Concatenate all rows:
```rust
let expected_row_concat_array = array!["1x11x2".to_owned(), "2x12x2".to_owned()]
let expected_col_concat_array = array!["1x12x1".to_owned(), "1x22x2".to_owned()]
```

**Comment by adamreichold** [comment]
Please have a look at the `ArrayBase::rows`, `ArrayBase::columns`, etc. methods which enable access to the elements of each row/column/etc.

This will most likely end up looking differently from what you expect as arbitrary operations on arbitrary types are not implemented on the arrays/views themselves (in contrast to some of the numeric operations where that makes sense):

```rust
let concat_rows = Zip::from(array.rows()).map_collect(|row| {
    row.iter().fold(String::new(), |mut acc, val| {
        acc.push_str(val);
        acc
    })
});

let concat_cols = Zip::from(array.columns()).map_collect(|col| {
    col.iter().fold(String::new(), |mut acc, val| {
        acc.push_str(val);
        acc
    })
});
```

**Comment by ibarrond** [comment]
Well, the hints you shared already constitute a good first approach to my question. Thanks for answering!
