### ISSUE TITLE
split into N roughly equal views

### ISSUE THREAD

**Issue by TheFoolishPupil** [rust-ndarray/ndarray#1162]
hey there, I am looking to split an array view into N different views, where N is ofc greater than the size od the axis in which the split occurs. I was trying to see if I cant avoid implementing this functionality myself but can't seem to find anything in the docs. Thought I would ask here before writing it myself. Thanks!

**Comment by jturner314** [comment]
Will you please clarify exactly what you're trying to achieve? For example, will you please provide the shape of an input view and the shapes of the desired output views?

Here are a few methods which may be of interest:

- [`axis_chunks_iter`](https://docs.rs/ndarray/0.15.4/ndarray/struct.ArrayBase.html#method.axis_chunks_iter)
- [`exact_chunks`](https://docs.rs/ndarray/0.15.4/ndarray/struct.ArrayBase.html#method.exact_chunks)
- [`split_at`](https://docs.rs/ndarray/0.15.4/ndarray/type.ArrayView.html#method.split_at)

**Comment by TheFoolishPupil** [comment]
Thanks for the response! For clarification, say I have a 2 dimensional array of shape (4, 13), and I wish to split it into 6 parts along Axis(1). Then I would like to produce 6 arrays; 5 with shape (4, 2) and a 1 with shape (4, 3). Hopefully I got those axis/shapes right and that the clarification is understandable :)

It looks like [axis_chunks_iter](https://docs.rs/ndarray/0.15.4/ndarray/struct.ArrayBase.html#method.axis_chunks_iter) may very well be what I am looking for, I will have a closer look at it.

**Comment by jturner314** [comment]
Thanks for the clarification. `axis_chunks_iter` is very close to what you've described, although the last chunk may be smaller than the others (rather than larger, as in your example). I assume that, since you've closed this issue, `axis_chunks_iter` meets your needs.

**Comment by TheFoolishPupil** [comment]
Yes it did in essence. I end up implementing my desired behavior roughly as follows. 
```rust
let area = ndarray::Array2::<u32>::zeros((12,13));
let n = 4; // Assuming n >= 2

// Get the longest axis and its size
let (axis, axis_size) = area.shape().iter().enumerate().max_by_key(|(_,v)| *v).unwrap();

let splits = axis_size / n;
let rem = axis_size % n; 

if rem > 0 {
    let mut split = area.axis_chunks_iter(Axis(axis), splits);
    let last1 = split.next_back().unwrap();
    let last2 = split.next_back().unwrap();
    
    let split = split.map(|x| x.to_owned());
    let joint = concatenate(Axis(axis), &[last2, last1]).unwrap();
    
    let areas = split.chain([joint]).collect::<Vec<_>>();
} else {
    let areas = area.axis_chunks_iter(Axis(axis), splits).collect::<Vec<_>>();
}
```
