### ISSUE TITLE
Miri complains about stacked borrow

### ISSUE THREAD

**Issue by mulimoen** [rust-ndarray/ndarray#1178]
The following snippet fails when executing with miri on the latest nightly

```rust
use ndarray::*;

fn main() {
    let a1 = arr2(&[[1.0, 2.0], [3.0, 4.0]]);
    let a2 = arr2(&[[2.0, 3.0], [4.0, 5.0]]);
    
    a1.dot(&a2);
}
```
and results in `error: Undefined Behavior: attempting a read access using <16389> at alloc6883[0x48], but that tag does not exist in the borrow stack for this location`

I am not sure whether this is a bug in `ndarray` or a false positive in miri

[Playground link](https://play.rust-lang.org/?version=nightly&mode=debug&edition=2021&gist=9d094dba4067be088a7958786bcd3f85)

**Comment by akern40** [comment]
This SB violation does not reproduce on `0.16.1`; closing in favor of resolving all Miri issues in #1372 via #1446.

**Comment by akern40** [comment]
But thank you for raising the issue!
