### ISSUE TITLE
Create an Array2 from an ArrayView2

### ISSUE THREAD

**Issue by daniellga** [rust-ndarray/ndarray#1193]
Hi! What would be the most efficient way to create an Array2 containing the same elements as an ArrayView2? Right now what I am doing is the following double for loop.
```
let new_array = Array2::<f64>::zeros((arr.nrows(), arr.ncols()))

for row in 0..arr.nrows() {
    for col in 0..length {
        new_array[[row , col]] = arr[[row, col]];
    }
 }
```

**Comment by jturner314** [comment]
Use the [`.to_owned()`](https://docs.rs/ndarray/0.15.6/ndarray/struct.ArrayBase.html#method.to_owned) method.
