### ISSUE TITLE
Implement function numpy.nan_to_num

### ISSUE THREAD

**Issue by MichalLebeda** [rust-ndarray/ndarray#1203]
Hi
function like[ ```numpy.nan_to_num```](https://numpy.org/doc/stable/reference/generated/numpy.nan_to_num.html) would be very useful so we dont have to replace NaNs by hand

**Comment by nilgoyette** [comment]
The maintainers are not really interested in adding methods that can easily be coded, like

    arr.mapv_inplace(|v| if v.is_nan() { 0.0 } else { v });

Moreover, do we add 2 methods: inplace (mut) and copy? And do we always replace by 0.0 or some arguments? And what about infinity? IMO, in this case, it is much simpler to code exactly what you need.
