### ISSUE TITLE
Translating `numpy.reshape(-1)`

### ISSUE THREAD

**Issue by mdrokz** [rust-ndarray/ndarray#1236]
Hi im converting an ML model to rust and there is this method which transposes & reshapes the array

```python
def rotate_vertices(vertices, theta, anchor=None):
	'''rotate vertices around anchor
	Input:	
		vertices: vertices of text region <numpy.ndarray, (8,)>
		theta   : angle in radian measure
		anchor  : fixed position during rotation
	Output:
		rotated vertices <numpy.ndarray, (8,)>
	'''
	v = vertices.reshape((4,2)).T
	if anchor is None:
		anchor = v[:,:1]
	rotate_mat = get_rotate_mat(theta)
	res = np.dot(rotate_mat, v - anchor)
	return (res + anchor).T.reshape(-1)
```

whats the ndarray equivalent of this line `return (res + anchor).T.reshape(-1)` ?

**Comment by Muthsera** [comment]
Hi, haven't tested anything but I found the method `t` and `into_shape` in the docs.
So I guess something like
```
// ...
res += anchor;
return res.t().into_shape(res.len());
```
should do the job.

**Comment by mdrokz** [comment]
> Hi, haven't tested anything but I found the method `t` and `into_shape` in the docs. So I guess something like
> 
> ```
> // ...
> res += anchor;
> return res.t().into_shape(res.len());
> ```
> 
> should do the job.
> 
> Alternatively there is `reshape` if you use an `ArcArray` specifically.

yeah that works for me, thanks alot !
