### ISSUE TITLE
problem for using sort-axis examples.

### ISSUE THREAD

**Issue by johnsonchak** [rust-ndarray/ndarray#1257]
hi, i am a new programer in rust.

i try to use sort-axis examples for my 2-d array but the complier tell me "unresolved import `rawpointer`"...

is there any api for sort 2-d array in ndarray now?

thank you

**Comment by nilgoyette** [comment]
Hi @johnsonchak. Sorry for the delay! The [sort-axis example](https://github.com/rust-ndarray/ndarray/blob/master/examples/sort-axis.rs) uses some extern crates, like `rawpointer`. You simply need to add it as a dependency to your Cargo.toml. If you don't know how to do that, start by the reading the excellent rust documentation and online book.
