### ISSUE TITLE
`BitVec` support for `ndarray`?

### ISSUE THREAD

**Issue by JohnScience** [rust-ndarray/ndarray#1258]
There is a [`bitvec`](https://crates.io/crates/bitvec) crate which offers space efficient storage for one-dimensional `bool` arrays and vectors. I'm contracted for a project which would benefit from `BitArrayD` analogous to `ArrayD`. Eventually we might consider the possibility of implementing it. Would this be a valuable addition to `ndarray` from your perspective?

**Comment by bluss** [comment]
How much of ndarray do you think you can reuse with this change?

**Comment by akern40** [comment]
@JohnScience is this still of interest or planned? If not, I would like to close to help clean up the issues backlog, since there has been no further activity.

**Comment by JohnScience** [comment]
> @JohnScience is this still of interest or planned? If not, I would like to close to help clean up the issues backlog, since there has been no further activity.

It was implemented but ended up being closed-source.
