### ISSUE TITLE
`parallel` module not found

### ISSUE THREAD

**Issue by Ebanflo42** [rust-ndarray/ndarray#1266]
Here is my `Cargo.toml` for a minimal reproducible example:

```
[package]
name = "ndarray_repro"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"
```

`cargo --version` is `cargo 1.67.1 (8ecd4f20a 2023-01-10)`

To demonstrate the issue I basically copied the example from the `parallel` documentation:

```
use ndarray::Array2;
use ndarray::parallel::prelude::*;
use ndarray::{linalg::*, iter::*};


fn main() {
    let mut a = Array2::<f64>::zeros((128, 128));

    a.par_map_inplace(|x| *x = x.exp());
    a.par_mapv_inplace(f64::exp);

    a.par_iter_mut().for_each(|x| *x = x.exp());
}
```

The first error from `cargo` is pretty direct:

```
error[E0433]: failed to resolve: could not find `parallel` in `ndarray`
 --> src/main.rs:2:14
  |
2 | use ndarray::parallel::prelude::*;
  |              ^^^^^^^^ could not find `parallel` in `ndarray`
```

No error is called on the use of `linalg` or `iter`. I guess I must be doing something very wrong, but it makes it look like the `parallel` module was not included in the latest release?

**Comment by adamreichold** [comment]
You need to enable the `rayon` feature to access that module, e.g.

```toml
ndarray = { version = "0.15", features = ["rayon"] }
```
