### ISSUE TITLE
select_mut?

### ISSUE THREAD

**Issue by Sabn0** [rust-ndarray/ndarray#1284]
Hi,
Any chance you would support a mutable selection, similar to the currently available select()? Currently I see available:
1) select() is great if I want a view of non-consecutive indices, but the resulting view is of course only a view.
2) slice_mut() gives you this read-write option, but only excepts ranges of consecutive indices...

Thanks

**Comment by adamreichold** [comment]
> select() is great if I want a view of non-consecutive indices, but the resulting view is of course only a view.

I think the returned array is not a view at all, it is a new array into which copies of the selected elements have been written.

> Any chance you would support a mutable selection

I think the main issue here is that for `select_mut` returning e.g. `Array<&mut A, D>`, one would need to check that `indices` are distinct at runtime and panic if they are not to avoid handing out multiple mutable references to the same element. This would require taking `&mut [Ix]` to be able to sort them in O(n log n) or checking for duplicates in O(n^2) where n is the number of indices.

Meaning it just is not an obvious API and one can build one's preferred variant on top of the existing API using e.g. `Array::get_mut` and adjusting the lifetimes via raw pointers.

**Comment by Sabn0** [comment]
Regarding select() - you are right, what I meant is that those are -copies- of the original instance.
I get the point about distinct indices. For now I will keep looping through my non-consecutive indices and slicing mutably.
Thank you

**Comment by benkay86** [comment]
`slice_mut()` does not necessarily require consecutive indices, just some regular pattern of indices, see [the documentation on slicing](https://docs.rs/ndarray/latest/ndarray/struct.ArrayBase.html#slicing).  You might also be able to use [`multi_slice_mut()`](https://docs.rs/ndarray/latest/ndarray/struct.ArrayBase.html#method.multi_slice_mut) if you need multiple, disjoint slices.

In general I don't think it's possible to arbitrarily index into an array without making a copy.  Slicing along some axis or regular pattern works by encoding the view in terms of a starting index, length, shape, and stride that linear algebra libraries like BLAS and LAPACK can understand.  If you can't do that then you are left with copying the array.

**Comment by adamreichold** [comment]
> In general I don't think it's possible to arbitrarily index into an array without making a copy. Slicing along some axis or regular pattern works by encoding the view in terms of a starting index, length, shape, and stride that linear algebra libraries like BLAS and LAPACK can understand. If you can't do that then you are left with copying the array.

There is the option of allocating a new array containing references into the original one, i.e. `Array<&mut T, D>`.

**Comment by Sabn0** [comment]
I have found a solution for what I needed, thank you both for your elaborated explanations.
