### ISSUE TITLE
Axis iter not working properly

### ISSUE THREAD

**Issue by JosephChotard** [rust-ndarray/ndarray#1285]
I would assume that `axis_iter` and `map_axis` would work in similar ways but they don't seem to.

```
let v = array![
    [[0.5, 0.2, 0.3], [0.4, 0.5, 0.6], [0.7, 0.8, 0.9]],
    [[0.0, 0.0, 0.0], [1.0, 1.0, 1.0], [0.7, 0.8, 0.9]]
];

println!("Map");
v.map_axis(Axis(2), |v| {
   println!("map: {:?}", v);
   5
});
println!("Iter");
v.axis_iter(Axis(2)).for_each(|v| {
    println!("iter: {:?}", v);
});
```

I would expect the `map_axis(Axis(2), ...` and `axis_iter(Axis(2))` to return the same thing but the output for iter is different from map

```
Map
map: [0.5, 0.2, 0.3], shape=[3], strides=[1], layout=CFcf (0xf), const ndim=1
map: [0.4, 0.5, 0.6], shape=[3], strides=[1], layout=CFcf (0xf), const ndim=1
map: [0.7, 0.8, 0.9], shape=[3], strides=[1], layout=CFcf (0xf), const ndim=1
map: [0.0, 0.0, 0.0], shape=[3], strides=[1], layout=CFcf (0xf), const ndim=1
map: [1.0, 1.0, 1.0], shape=[3], strides=[1], layout=CFcf (0xf), const ndim=1
map: [0.7, 0.8, 0.9], shape=[3], strides=[1], layout=CFcf (0xf), const ndim=1
Iter
iter: [[0.5, 0.4, 0.7],
 [0.0, 1.0, 0.7]], shape=[2, 3], strides=[9, 3], layout=Custom (0x0), const ndim=2
iter: [[0.2, 0.5, 0.8],
 [0.0, 1.0, 0.8]], shape=[2, 3], strides=[9, 3], layout=Custom (0x0), const ndim=2
iter: [[0.3, 0.6, 0.9],
 [0.0, 1.0, 0.9]], shape=[2, 3], strides=[9, 3], layout=Custom (0x0), const ndim=2
```

Map returns what I expect but not iter

Am I missing something?

**Comment by JosephChotard** [comment]
Ah my bad, subviews and axis are different. confusing names. Not sure what I should use to replicate map but as an iter. Will close as separate discussion

**Comment by adamreichold** [comment]
`axis_iter` iterates along the given axis yielding sub views orthogonal to that axis. `map_axis` always yields one-dimensional vectors where each one "pierces" the array along the given axis. So in short, for `axis_iter`, the axis is the direction of iteration whereas for `map_axis`, the axis it is the direction of sub views (or the direction of reduction).

**Comment by JosephChotard** [comment]
Yes, I think I was looking for `lanes` instead @adamreichold
