### ISSUE TITLE
Implement take

### ISSUE THREAD

**Issue by WillAyd** [rust-ndarray/ndarray#1293]
Not sure if there is an equivalent way to sort an array by another, but numpy has take as a convenience function:

https://numpy.org/doc/stable/reference/generated/numpy.take.html

While ndarray has `slice` and `to_slice` methods, I don't think these are round-trippable the same way that take would be, since `to_slice` returns a primitive slice  whereas `slice` looks for a `SliceArg` argument

**Comment by nilgoyette** [comment]
I think what you are searching is [select](https://docs.rs/ndarray/latest/ndarray/struct.ArrayBase.html#method.select), no?

**Comment by WillAyd** [comment]
Ah thanks - yea I think that works. Appreciate the guidance
