### ISSUE TITLE
Callling clone on collapsed array also clones collapsed values

### ISSUE THREAD

**Issue by Janmajayamall** [rust-ndarray/ndarray#1302]
Callling clone on collapsed array also clones collaposed values. For example,

```
let mut a = Array2::<u64>::zeros((10, 100));
a.slice_collapse(s![..5, ..]);
// Calling clone on `a` clones all values including from subview `s![5.., ..]`
let b = a.clone();
```

Is this expected?

**Comment by bluss** [comment]
In general, yes.

**Comment by Janmajayamall** [comment]
ah, I seem to have landed on a situation where I can't move ownership of type that owns `Array2`. This means I can't use `slice_move`.

Is there an alternative that collpases the view and clones only restricted view? Or a way that I can copy only values in collapsed view?

**Comment by Janmajayamall** [comment]
Yup that's what I need. Thanks!
