### ISSUE TITLE
Is there any function similar to `numpy.memmap`

### ISSUE THREAD

**Issue by Boltzmachine** [rust-ndarray/ndarray#1334]
https://numpy.org/doc/stable/reference/generated/numpy.memmap.html

**Comment by adamreichold** [comment]
I think to do this, you will need to use the [`memmap2`](https://docs.rs/memmap2/latest/memmap2/) crate and unsafely create an array view over the memory map (the creation of which is already highly unsafe).

For better integration, we would need an alternative to [`OwnedRepr`](https://docs.rs/ndarray/latest/ndarray/struct.OwnedRepr.html) that is baked by a memory map instead a heap allocation.

**Comment by Boltzmachine** [comment]
Do you mean it is possible to implement this in my code through the current `ndarray` crate?

**Comment by adamreichold** [comment]
Yes, you can for example use e.g. `ArrayView(Mut)::from_slice_ptr` and `MmapRaw` but you wont be able to freely pass this around and instead manually need to ensure that the `MmapRaw` stays alive long enough so that your array views are valid.

**Comment by Boltzmachine** [comment]
Thanks. Will try
