### ISSUE TITLE
Matrix determinant

### ISSUE THREAD

**Issue by guri-dominic** [rust-ndarray/ndarray#1336]
How do I get a matrix determinant? I am new to rust, and I am trying to implement a basic numpy script in rust.The hints I get from rust analyzer suggest that `m.det()` is not valid.
The documentation doesn't seem to have a clear example for such a simple linear algebra operation. Am I missing something in the documentation?

**Comment by nilgoyette** [comment]
ndarray offers a minimal set of tools that can be used by anyone. For more "complex" statistical or mathematical functions, there are other libraries, such as [ndarray_linalg](https://docs.rs/ndarray-linalg/latest/ndarray_linalg/index.html) which has a `det` [method](https://docs.rs/ndarray-linalg/latest/ndarray_linalg/solve/trait.Determinant.html).

**Comment by guri-dominic** [comment]
Thank you for the clarification
