### ISSUE TITLE
Question: is there anyway to convert from python ndarray to rust ndarray?

### ISSUE THREAD

**Issue by WindSoilder** [rust-ndarray/ndarray#1350]
Assume that I have something in python ndarray:
```python
import pandas as pd
df =  pd.DataFrame({'a': [1, 2.0, 3.22]})
values = df.values
```
The value is something the following:
```python
array([[1.  ],
       [2.  ],
       [3.22]])
```

I wonder is there any way to convert it into rust ndarray?

I'm thinking about covnert from python numpy ndarray to bytes(`values.tobytes()`) firstly, but I'm failed to convert from such bytes to ndarray.

**Comment by adamreichold** [comment]
If you want Rust code to interact directly with Python data structures, bindings for the Python interpreter are required. [PyO3](https://pyo3.rs) is one such project for which an add-on crate [`numpy`](https://github.com/PyO3/rust-numpy) is available which supports direct access of NumPy arrays as `ArrayView`s.

**Comment by WindSoilder** [comment]
Oh, sorry I'm asking in a wrong place
