### ISSUE TITLE
Implement product_axis

### ISSUE THREAD

**Issue by unrenormalizable** [rust-ndarray/ndarray#1351]
product_axis is like sum_axis but for product. [numpy](https://numpy.org/doc/stable/reference/generated/numpy.prod.html) has this implemented. it is the torch.prod equivalent with the dim argument. It will be good to have this implemented. 

Some of the libraries I work with - mainly burn - is adding this functionality but i have to implement it for ndarray in the burn codebase.

**Comment by nilgoyette** [comment]
Please update your issue with more details about `product_axis`. A description, a link, etc. We shouldn't have to wonder what you meant by that.

**Comment by unrenormalizable** [comment]
> Please update your issue with more details about `product_axis`. A description, a link, etc. We shouldn't have to wonder what you meant by that.

done. lmk if more details are required.

**Comment by nilgoyette** [comment]
I think this is a good idea, since we have `sum` and `sum_axis`.

I was about to code it with `fold_axis` or `map_axis`, but it seems that we can use that [function](https://docs.rs/ndarray/latest/src/ndarray/numeric/impl_numeric.rs.html#243-258) as a basis.

**Comment by akern40** [comment]
Hello! Would love to continue contributing, and looking for some more low-hanging fruit; just submitted a PR to close this, please let me know if there's any feedback.
