### ISSUE TITLE
Unsound usages of `VecFromRawParts`

### ISSUE THREAD

**Issue by llooFlashooll** [rust-ndarray/ndarray#1426]
Hi, I am scanning the ndarray in the latest version with my own static analyzer tool.

Unsafe conversion found at: src/data_repr.rs#L137
``` rust
fn take_as_vec(&mut self) -> Vec<A>
{
   let capacity = self.capacity;
   let len = self.len;
   self.len = 0;
   self.capacity = 0;
   unsafe { Vec::from_raw_parts(self.ptr.as_ptr(), len, capacity) }
}
```

This unsound implementation of `Vec::from_raw_parts` would create a dangling pointer issues if the `ptr` is dropped automatically or is empty. The 'mem::forget' function can be used to avoid the issue.

This would potentially cause [undefined behaviors](https://doc.rust-lang.org/reference/behavior-considered-undefined.html) in Rust. If we further manipulate the problematic converted types, it would potentially lead to different consequences such as uaf or double free. I am reporting this issue for your attention.

**Comment by bluss** [comment]
Thanks for the note - do you think that's an issue here, could you demonstrate the problem? ManuallyDrop is used several places in the same file (preferable to mem::forget in most cases).

**Comment by bluss** [comment]
OwnedRepr is created from a Vec (OwnedRepr::from), which should be the basis for why this conversion is sound.

**Comment by bluss** [comment]
No worries, thank you for taking a look, it helps!
