### ISSUE TITLE
HWC to 1CHW Speed

### ISSUE THREAD

**Issue by marcown** [rust-ndarray/ndarray#1428]
Hey there,

I have the following code (converting an image in hwc form to 1chw array f32):

```rust
fn hwc_to_1chw(image_data: *const u8, width: u32, height: u32) -> Array4<f32> {
    let image_vec = unsafe { std::slice::from_raw_parts(image_data, (width * height * 3) as usize).to_vec() };
    let my_array = Array3::from_shape_vec((height as usize, width as usize, 3), image_vec).unwrap();
    let my_array = my_array.permuted_axes([2, 0, 1]).insert_axis(Axis(0));

    let const_divide = 255.0;

    let array = my_array.map(|&pixel| pixel as f32 / const_divide );
    array
}

```

I am quite new to rust and rust ndarray (its prototyping so ignore the naming etc. for the moment). 

The main time is consumed here: 

let array = my_array.map(|&pixel| pixel as f32 / const_divide );

for my pc and a 600x300 image it takes 3-5ms, is there any way to make it faster? And is this even the right place to ask? 

Thanks in advance!

**Comment by marcown** [comment]
closed, building with release is fast enough (<1ms)

**Comment by robertknight** [comment]
Aside from the release build issue which you already found, division is an expensive operation. When dividing many elements by the same value, converting to multiplication by the reciprocal can be profitable, if the very small difference in the result is acceptable.

```rs
let const_recip = 1. / const_divide;
let array = my_array.map(|&pixel| pixel as f32 * const_recip);
```
