### ISSUE TITLE
solve() seems missing in 0.16

### ISSUE THREAD

**Issue by PegasusPlusUS** [rust-ndarray/ndarray#1444]
My simple program main.rs try to resolve linear equations:

``` main.rs
use ndarray::prelude::*;
use ndarray_linalg::*;

fn main() {
    let a: Array2<f64> = array![[3.0, 2.0], [1.0, 2.0]];
    let b: Array1<f64> = array![5.0, 5.0];
    let x = a.solve(&b).unwrap();  // Solve the system A * x = B
    println!("Solution: {:?}", x);
}
```

It works when I use ndarray 0.15 and ndarry_linalg 0.15:
``` Cargo.toml
[package]
name = "solve"
version = "0.1.0"
edition = "2021"

[dependencies]
ndarray = "0.15"  # Or whichever version you're using
ndarray-linalg = { version = "0.15", features = ["openblas-system"] }
pkg-config = "0.3"

```

When I try to use recent ndarray version 0.16, main.rs can't compile:
error[E0599]: no method named `solve` found for struct `ArrayBase` in the current scope
 --> src/main.rs:7:15
  |
7 |     let x = a.solve(&b).unwrap();  // Solve the system A * x = B
  |               ^^^^^ method not found in `ArrayBase<OwnedRepr<f64>, Dim<[usize; 2]>>`

**Comment by akern40** [comment]
Unfortunately this is a version mismatch between `ndarray` and `ndarray-linalg`; you cannot use `ndarray` version 0.16 with `ndarray-linag` until `linalg` bumps its dependencies. See [this issue on `ndarray-linalg`](https://github.com/rust-ndarray/ndarray-linalg/issues/380) for more, and [this issue](https://github.com/rust-ndarray/ndarray-linalg/issues/381) on the maintainership discussion there.

**Comment by PegasusPlusUS** [comment]
Thanks for answering. Before committing this issue, I also tried using both "0.16" version of ndarray_linalg and ndarray together, the same compiler error, so I guess there's some interface changing that break old examples (ChatGPT told me the simple solve sample)

**Comment by akern40** [comment]
Ya it's because of the minor version change between 0.15 and 0.16, I believe. You can read more [here](https://doc.rust-lang.org/cargo/reference/resolver.html#semver-compatibility) about Rust's dependency resolution between versions.
