### ISSUE TITLE
View of Vec

### ISSUE THREAD

**Issue by akern40** [rust-ndarray/ndarray#1467]
To my surprise, there is no way to get a (read-only) 1D view of a Vec by reference; i.e., no way to get `ArrayView<'a, A, Ix1>` from `vec: &'a Vec<A>`; the same goes for slices. The `Vec` and slice documentation seems to indicate that if you get a slice (either from a passed-in slice or from `vec.as_slice()`) and then use `.as_ptr()`, you can read from that pointer as long as you preserve the lifetime of the slice.

Having this capability would be an important step towards zero-copy, by-reference operations using allocated vectors and slices.

**Comment by akern40** [comment]
Nope, this is not true. You can use `ArrayView1::from(_)`, although I can't find where this is documented in the docs.

**Comment by jturner314** [comment]
Docs here: [`ArrayView::from`](https://docs.rs/ndarray/0.16.1/ndarray/type.ArrayView.html#method.from). The docs are a bit weird for the type aliases -- some things show only on the aliases, not `ArrayBase`, and only for the alias that matches the source code, even if there are other equivalent aliases. There are some useful tables in the `ArrayBase` docs listing most of the conversions, e.g. [Conversions Between Arrays and `Vec`s/Slices/Scalars](https://docs.rs/ndarray/0.16.1/ndarray/struct.ArrayBase.html#conversions-between-arrays-and-vecsslicesscalars).
