### ISSUE TITLE
Provide a quick reference

### ISSUE THREAD

**Issue by gnzlbg** [rust-ndarray/ndarray#310]
I find the learning curve to the library to be very steep. 

I think it would be worth it to provide a [Quick Reference (e.g. like in Eigen3)](https://eigen.tuxfamily.org/dox-devel/group__QuickRefPage.html) that shows how the building blocks are supposed to be used together to achieve common tasks.

This could then be linked to the relevant parts of the docs.

**Comment by bluss** [comment]
The ArrayBase doc has elements of that, but no tables.

**Comment by nilgoyette** [comment]
Closing this issue because we already have

- [ndarray_for_numpy_users](https://docs.rs/ndarray/latest/ndarray/doc/ndarray_for_numpy_users/index.html#)
- [Quickstart tutorial](https://github.com/rust-ndarray/ndarray/blob/master/README-quick-start.md)
