### ISSUE TITLE
More examples, simple examples

### ISSUE THREAD

**Issue by jaroslaw-weber** [rust-ndarray/ndarray#327]
It would be great to look at the documentation and see few basic examples of how to use the library without trying to decode the advanced code examples in repo.

**Comment by nilgoyette** [comment]
Closing this issue because we already have

- [ndarray_for_numpy_users](https://docs.rs/ndarray/latest/ndarray/doc/ndarray_for_numpy_users/index.html#)
- [Quickstart tutorial](https://github.com/rust-ndarray/ndarray/blob/master/README-quick-start.md)
