### ISSUE TITLE
Alga integration

### ISSUE THREAD

**Issue by milibopp** [rust-ndarray/ndarray#410]
Would you be open to integrate ndarray with [alga](https://docs.rs/alga/0.5.2/alga/)? The point of this would be to enable people to write generic code in terms of vector spaces etc. and be able to pass ndarray's `Array` type in.

I have been looking at this for various libraries now and as ndarray already supports broadcasting the integration should be a bit easier. But I would have to look into the details, of course.

**Comment by bluss** [comment]
I don't know `alga` but thanks for reaching out — algebra is not my prioritized approach to generic programming in numerics. We have some basics to take care of first — for example being able to treat `f64` and `Complex<f64>` both as complex numbers.

What does integrating with alga mean for us?

**Comment by aepsil0n** [comment]
Ah, I see… `alga` does have abstractions for fields, too. ("field" is not meant too mathematically here, as floating point numbers do not strictly satisfy the algebraic properties exactly.)

In addition, it does go into [a lot of detail](https://docs.rs/alga/0.5.2/alga/general/index.html) modelling the whole tower of algebraic structures. There are [abstractions for linear algebra](https://docs.rs/alga/0.5.2/alga/linear/index.html) such as a vector spaces, which are compositions of the more fundamental structures.

In practice, integrating with alga would mean to implement the traits provided by alga (possibly as an optional feature). Not all of them have to be implemented explicitly, as some are mere compositions with blanket implementations.

I would be willing to put in the work to see whether it fits and, if so, do that implementation. But it is a bit of churn and so I wanted reach out first to see whether integrating this into ndarray is an option at all. My motivation is to be able to write generic algorithms for linear algebra that can used with different algebra crates.

**Comment by aepsil0n** [comment]
Completely agree with you on the loose coupling issue. It would be nice if Rust allowed an integration like this to be a separate crate. One option to do this out of crate is to make a wrapper, which has a ton of downsides, too.

I have started doing a wrapper implementation as a small prototype to test the integration. This is also a good way to make sure one only relies on the public API of ndarray. Thus there should not be any extra barrier to refactoring – unless you want to do API-breaking refactorings, of course, in which case all bets are off, especially if the semantics change.

To be honest I can only speculate on the meaning of "stable" in the `MatrixMut` docs. By definition of the trait it should mean those matrices, where these methods are fine to expose. As a counter example, if you had a `SymmetricMatrix`, it should probably not implement such a trait.

**Comment by bluss** [comment]
We have goals and we have compromises - no point in wrappers if it is a torture to impl or use.

**Comment by nilgoyette** [comment]
Closing this issue

- No news from OP in 5 years
- alga has been abandonned in favor of simba, if I'm not mistaken
