### ISSUE TITLE
Why not moving this repository to a Github organization?

### ISSUE THREAD

**Issue by nbro** [rust-ndarray/ndarray#424]
#### Reasons

1. It would be more clear that this isn't the work of just one person, and hence it may be more "attractive".

2. Other similar packages (for numerical computations) may be associated with the same organization.

**Comment by hamilton** [comment]
+1 to this. I've had some recent experiences where I moved repos into dedicated orgs. It is a strong social signal to devs that there is not a two-class system for open-source contributions, and that everyone involved is taking this seriously enough to do proper management.

Glad to have found this lib! I'm working on an adjacent project that might be able to utilize ndarray here, and will be sharing this repository w/ an interested contributor.

**Comment by paddyhoran** [comment]
+1 to this too

**Comment by nbro** [comment]
@hamilton and @paddyhoran, I think you should have given the "thumbs up" to the issue.

**Comment by nbro** [comment]
This project has finally been moved to an organisation, so this issue can be closed.
