### ISSUE TITLE
Change ArrayBase.ptr to NonNull type

### ISSUE THREAD

**Issue by jturner314** [rust-ndarray/ndarray#434]
Rust 1.25 introduces a [`NonNull`](https://doc.rust-lang.org/stable/std/ptr/struct.NonNull.html) type, which represents a pointer that must always be non-null. It would be nice to switch the `ArrayBase.ptr` field to type `NonNull<S::Elem>` to indicate that the pointer must always be non-null.

However, I'm not quite sure about the implications of `NonNull<T>` being "covariant over `T`". After reading [this page in the nomicon](https://doc.rust-lang.org/nomicon/subtyping.html), I think this is okay for `Array`, `ArrayView`, `ArrayViewMut`, and `ArcArray`, but I'm not sure that it's okay in general for arbitrary `S: Data`.

**Comment by bluss** [comment]
Sure, using NonNull should be good for us, don't see a problem with that. We need to remember to highlight the non-null requirement in `ArrayView::from_shape_ptr`. I'll have a think about if we already de facto require that pointer to be null (it certainly is non-null in all the safe ways of making an ArrayView).

**Comment by bluss** [comment]
NonNull was already listed over in #414, but I updated it to link to this issue as the specific one for that point.

**Comment by bluss** [comment]
(There is no “arbitrary S: Data” yet, because the Data trait is documented to be for our own purpose and we control all its implementations.)

**Comment by jturner314** [comment]
> There is no “arbitrary S: Data” yet

Specifically, I'm thinking about the raw pointer array views we discussed in #388, for which `NonNull` might not make sense. There may also be other `Data` types that we want to add in the future.
