### ISSUE TITLE
Iteration tutorial?

### ISSUE THREAD

**Issue by holtgrewe** [rust-ndarray/ndarray#471]
I have a 2D array and I want to iterate along axis 0 in reverse order. I could not find out how to do this elegantly with the documentation. Could you point me to the corresponding place in the documentation?

Thanks!

**Comment by jturner314** [comment]
You can do this most clearly with a combination of [`.axis_iter()`](https://docs.rs/ndarray/0.11.2/ndarray/struct.ArrayBase.html#method.axis_iter) and [`.rev()`](https://doc.rust-lang.org/std/iter/trait.Iterator.html#method.rev), e.g. `arr.axis_iter(Axis(0)).rev()`. An alternative approach is to [`.slice()`](https://docs.rs/ndarray/0.11.2/ndarray/struct.ArrayBase.html#method.slice) or [`.slice_axis()`](https://docs.rs/ndarray/0.11.2/ndarray/struct.ArrayBase.html#method.slice_axis) with a negative step to obtain a reversed review, and then call `.axis_iter()`.

**Comment by nilgoyette** [comment]
@jturner314 I wanted to answer this question so I tested myself

    for row in arr.genrows().into_iter().rev() {

but it fails with:

> the trait bound `ndarray::iter::LanesIter<'_, {float}, ndarray::Dim<[usize; 1]>>: std::iter::DoubleEndedIterator` is not satisfied

I know `axis_iter()` is equivalent to `genrows()` and `gencolumns()`, but I prefer well-named functions when I can use them. Any reason why they are not working here? The documentation says:

> Most NdProducers are iterable (implement IntoIterator) but not directly iterators. [...] The natural exception is one dimensional producers, like AxisIter, which implement Iterator directly (AxisIter traverses a one dimensional sequence, along an axis, while producing multidimensional items).

I would have thought that `genrows()` and `gencolumns()` could be used exactly like `axis_iter(Axis(?))`.
