### ISSUE TITLE
Clippy identifying an immediate dereferencing of a reference

### ISSUE THREAD

**Issue by Libbum** [rust-ndarray/ndarray#474]
Just did a clippy lint over a project I'm trying to dust off, and managed to hit a whole heap of these:

```rust
warning: immediately dereferencing a reference
   --> src/grid.rs:342:43
    |
342 |                         let l = phi.slice(s![lx - 2..lx + 3, ly - 2..ly + 3, lz - 2..lz + 3]);
    |                                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^
    |
    = help: for further information visit https://rust-lang-nursery.github.io/rust-clippy/v0.0.212/index.html#deref_addrof
    = note: this error originates in a macro outside of the current crate (in Nightly builds, run with -Z external-macro-backtrace for more info)
help: try this
    |
39  | & match $ r {
40  | r => {
41  | s ! [
42  | @ parse $ crate :: SliceNextDim :: next_dim ( & r , $ dim ) , [
43  | $ ( $ stack ) * s ! ( @ convert r ) , ] $ ( $ t ) * ] } } } ;
```

The macro it's highlighting is [this one](https://github.com/bluss/ndarray/blob/df55183938e42a98c8bb53254c994b36ee40e85e/src/slice.rs#L623-L628), but adding the suggested additional ampersand isn't the entire solution (if it is at least part of it).

My macro capability is close to 0, so hopefully someone else can identify a fix.

**Comment by jturner314** [comment]
My guess is that this warning is a result of [this workaround](https://github.com/bluss/ndarray/blob/df55183938e42a98c8bb53254c994b36ee40e85e/src/slice.rs#L642-L644) for compiler bug rust-lang/rust#23014. I just tried removing the extra `*&` on the latest stable compiler (1.27), but the workaround is still necessary.

I just tried a few different ways of adding an annotation to tell clippy to ignore this, but didn't have much success getting anything that allowed the tests to compile. (The compiler gave a variety of errors for my attempts, the most common one being `error[E0658]: attributes on expressions are experimental. (see issue #15701)`.)

If anyone can find a way to add an attribute to tell clippy to ignore this, please feel free to submit a PR.

**Comment by lambda-fairy** [comment]
I recall that Clippy has special logic to ignore macro-expanded code. Could that logic be added to this lint?

(I also notice that this bug is two years old, so that may have been done already.)

**Comment by bluss** [comment]
Closing since the macro involved etc has changed, probably not relevant now.
