### ISSUE TITLE
and_broadcast_mut for Zip

### ISSUE THREAD

**Issue by millardjn** [rust-ndarray/ndarray#478]
Currently Zip has no mutable equivalent for the `and_broadcast` method, which is presumably to allow it to safely be `split()` and parallelized. However this makes some calculations difficult. The examples below are for backprop through a broadcast-able element-wise multiplication, but the problem appears as a pattern often.

Currently I'm looking at using this:
```
unsafe{
	let input2_grad = data.get_mut(&self.input2_id.gradient_id())?;

	// do not split/parallelise this Zip!
	Zip::from(&input1)
		.and(&output_grad)
		.and_broadcast(&input2_grad)
		.apply(|input1, out_grad, input2_grad| {
			let input2_grad = input2_grad as *const f32 as *mut f32;
			*input2_grad += input1 * out_grad;
		});
}
```
which works correctly, but also has UB written all over it depending on how Zip is implemented internally (I realize Zip owes me nothing here). 

The safe alternative I've found is:
```
let iter = input1.exact_chunks(input2.shape()).into_iter()
	.zip(output_grad.exact_chunks(input2.shape()));

for (input1_chunk, out_grad_chunk) in iter {
	Zip::from(&mut input2_grad)
		.and(&input1_chunk)
		.and(&out_grad_chunk)
		.apply(|input2_grad, input1, out_grad| {
			*input2_grad += input1 * out_grad;
		});
}
```
which is catastrophically (over 30x) slower for some cases.

So my questions are:
 * is there a safe high performance workaround that I've missed?
 * would it be possible to add a `and_broadcast_mut()` method which would set a flag or something which makes `split()` panic?

**Comment by bluss** [comment]
In short: .and_broadcast_cell ? Or General ArrayViewMut -> ArrayView of Cells?

**Comment by millardjn** [comment]
I think `ArrayViewMut<T>` borrowed as a `ArrayView<Cell<T>>` looks like quite a nice solution, and might even come in handy elsewhere. From [this](https://github.com/rust-lang/rfcs/blob/master/text/1789-as-cell.md#from_mut) it seems simple, are there any pitfalls in extending this to casting the backing array? I'll give implementing this a go.

**Comment by bluss** [comment]
We should be able to start with just an `ArrayViewMut::as_cell_view`, or whatever name feels best, method and try to plug it in the existing broadcast code. Ergonomics of Cells and value updates are of course not ideal.

I guess there is a chance these methods are being held back for technical or "unsafe code guidelines/formalization" reasons upstream. I can't spot any discussion along those lines though. The `Cell` has this attribute in Rust now, which is a stable attribute too: `#[repr(transparent)]`.
