### ISSUE TITLE
Implement ascontiguousarray() or contiguous() method

### ISSUE THREAD

**Issue by Rikorose** [rust-ndarray/ndarray#532]
See https://docs.scipy.org/doc/numpy/reference/generated/numpy.ascontiguousarray.html or https://pytorch.org/docs/stable/tensors.html#torch.Tensor.contiguous

A method like this is e.g. needed when passing &ndarray.as_slice() to an external api.

**Comment by andrei-papou** [comment]
@LukeMathWalker could you please take a look at the [PR](https://github.com/rust-ndarray/ndarray/pull/616)? Thanks.
