### ISSUE TITLE
ArrayView as Custom DST

### ISSUE THREAD

**Issue by jturner314** [rust-ndarray/ndarray#538]
It would be really nice if we could replace `ArrayView`/`ArrayViewMut` with custom dynamically-sized types. [RFC 2594](https://github.com/rust-lang/rfcs/pull/2594) is a current proposal for custom DSTs. The current version would work for const-dimensionality views but not for dynamic-dimensionality views (`IxDyn`).

I've asked about the dynamic dimensionality case and proposed a couple of ideas. @bluss Maybe you have some more ideas?

**Comment by bluss** [comment]
Just to note, it seems like the dynamic dimensional kind of view can never be a DST (due to the dynamic size and heap allocation of the metadata i.e the sizes and strides). That doesn't have to stop us from pursuing the rest.

**Comment by akern40** [comment]
While this is a very clear dream, custom DSTs were postponed in 2021 and there's not even a mention of them on the 2024 roadmap. With #879 coming in, we at least alleviate some of the pressure for DSTs and there's a clear path forward for unifying `ArrayView(Mut)` with `ArrayRef` if custom DSTs pop their heads back up.
