### ISSUE TITLE
Document reason for strongly typed `Axis`?

### ISSUE THREAD

**Issue by JP-Ellis** [rust-ndarray/ndarray#564]
While using `ndarray`, I was wondering why certain methods use the `Axis` type instead of just `usize`, especially given that `Axis` is just a simple wrapper around `usize`.  I tried looking into the documentation, and could not find any explanation; and searching through past issues/pull requests, I found just #91, #96 and #97 (though none of them given a clear reason why this is the case).

Would it be worth documenting this choice?  

And is there a reason why `From<usize>`/`Into<Axis>` isn't implemented for `Axis`/`usize`?

**Comment by bluss** [comment]
Doesn't axis doc have a short rationale?

**Comment by JP-Ellis** [comment]
All the documentation states is:

> All array axis arguments use this type to make the code easier to write correctly and easier to understand.

Looking through the functions which use the `Axis` type, I don't really see why it is all that necessary.
- A number of functions which  have the name `axis` in them, making the `Axis` type overly verbose in my opinion.  
  + [`invert_axis`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.invert_axis)
  + [`insert_axis`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.insert_axis)
  + [`remove_axis`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.remove_axis)
  + [`sum_axis`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.sum_axis)
  + [`std_axis`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.std_axis)
- Some function, although don't have the name `axis` in them, seem 'obvious enough' to me to not need the `Axis` type:
  + [`len_of`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.len_of)
  + [`stride_of`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.stride_of)
  + [`lanes`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.lanes)
- The only functions which I can see perhaps needing the `Axis` type are those with multiple arguments, though having said that none of them have overly complicated arguments so I don't really see the need for the `Axis` type:
  + [`subview`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.subview)
  + [`index_axis`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.index_axis)
  + [`select`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.select)

So ultimately, I still don't see why there's a need for `Axis` over just using `usize`, other than for the very last group of functions listed above.

**Comment by bluss** [comment]
Some good defenders of the newtype are IMO

- [`fn slice_axis/_mut(&self, Axis, Slice)`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.slice_axis)
- [`fn slice_axis_inplace/_mut(&mut self, axis: Axis, indices: Slice)`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.slice_axis_inplace)
- [`fn lanes/_mut(Axis)`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.lanes)
- [`fn axis_chunks_iter/_mut(&self, axis: Axis, size: usize)`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.axis_chunks_iter)
- [`fn fold_axis<B, F>(&self,     axis: Axis,     init: B,     fold: F)`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.fold_axis)

**Comment by jturner314** [comment]
Fwiw, I'd like to replace `.sum_axis(axis)` with `.sum_axes(axes)` in the future (and do the same for most/all of the other `_axis` methods), so we'll need to think about how to handle the `axes` parameter.

I do think it makes sense to keep a separate `.sum()` method because the return type is different (`A` instead of `Array<A, _>`).

An alternative to having separate `.sum()` and `.sum_axes(axes)` methods is to make the [return type be an associated type of the `axes` parameter, treating `()` as a special case](https://github.com/rust-ndarray/ndarray/issues/416#issuecomment-368163111), but I don't like that idea.

**Comment by JP-Ellis** [comment]
Thanks for the replies!

I still think that `Axis` as a type of a bit too verbose, but I also understand the desire for being a little more verbose for the sake of clarity.

I also really like the way `.sum_axes()` approaches this.

**Comment by max-sixty** [comment]
FWIW in xarray we follow a similar approach to Numpy:
- Don't have separate methods for `*_axis`
- Specify axes / dimensions on all reductions, either as a list, single item, or `None`. Where no axes / dimensions are given, all are reduced. Given there aren't optional args in rust, I think the corollary would be an `Axis` enum which could be any of those three options
- Unlike numpy, have _all_ operations return an array, even those that reduce to a scalar. That reduces the uncertainty about what type a method returns. IIUC in rust you could allow a coercion to the element type with `Into`
