### ISSUE TITLE
Result<D: Dimension> from a Vec<usize>

### ISSUE THREAD

**Issue by aldanor** [rust-ndarray/ndarray#569]
I'm trying to figure whether to use ndarray as an nd-array backend for hdf5-rs and so far things are looking good but there's a few weird hiccups.

One of them (unless I'm misunderstanding something here) is being unable to construct any dimension from a `Vec<usize>`. E.g., I'd want this to work:

```rust
pub fn read_arr<T, D>(&self) -> Result<Array<T, D>>
where
    D: Dimension,
    Vec<usize>: Into<StrideShape<D>>,
{
    let shape: Vec<usize> = query_the_shape()?;
    let vec = read_the_data()?;
    Ok(unsafe { Array::from_shape_vec_unchecked(shape, vec) })
}
```

And while this would work with `IxDyn`, with fixed dimensions it would fail with

```
expected struct `ndarray::dimension::dynindeximpl::IxDynImpl`, found array of 2 elements
```

because `Vec<usize>` is not convertible into `Dim<[_; 2]>`. Is there some elegant generic way of doing this? (as opposed to copy/pasting the logic for dyn / 0d / 1d / 2d / ...)

Maybe something like `TryFrom<>` would fit here? E.g., you can construct a 1-D shape from a `Vec<Ix>`, but only if this vector is of length 1, and an error is produced otherwise.

**Comment by jturner314** [comment]
The simplest way to do achieve your goal (constructing a fixed-dimension array starting with a `Vec` as the shape) would be to first construct a dynamic-dimension array and then convert it into a fixed-dimension array with [`.into_dimensionality()`](https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html#method.into_dimensionality), like this:

```rust
pub fn read_arr<T, D>(&self) -> Result<Array<T, D>>
where
    D: Dimension,
{
    let shape: Vec<usize> = query_the_shape()?;
    let data: Vec<T> = read_the_data()?;
    // `from_shape_vec_unchecked` would also work here, but make sure all the safety conditions will always be met.
    let array_d = ArrayD::from_shape_vec(shape, data)?;
    Ok(array_d.into_dimensionality::<D>()?)
}
```

Directly constructing an instance of arbitrary `D: Dimension` from a `Vec<usize>` is more difficult. We could add conversions from `Vec` in the future, but none exist right now. Something like this is the best I can come up with using the currently available methods:

```rust
fn dim_from_vec<D: Dimension>(v: Vec<usize>) -> Result<D, &'static str> {
    if let Some(ndim) = D::NDIM {
        if ndim != v.len() {
            return Err("length mismatch")
        }
    }
    // Construct an instance of `D` initialized with zeros.
    let mut dim = D::zeros(v.len());

    // Copy the data using `.assign()`:
    dim.as_array_view_mut().assign(&ArrayView1::from(&v));
    // or by iterating over indices:
    for i in 0..v.len() {
        dim[i] = v[i];
    }

    Ok(dim)
}
```

**Comment by aldanor** [comment]
Closing this for now (we've went with suggested options; it would be nice if more straightforward alternatives existed, but it's not critical).
