### ISSUE TITLE
Switch to criterion for benchmarks

### ISSUE THREAD

**Issue by jturner314** [rust-ndarray/ndarray#573]
I'd like to change the benchmarks from using `libtest` to using [`criterion`](https://github.com/bheisler/criterion.rs). `criterion` provides a lot more functionality, and its results are a lot easier to read. It can also run on stable, but I'll keep the benches nightly-only for the time being in order to be able to [use `real_blackbox`](https://bheisler.github.io/criterion.rs/book/user_guide/known_limitations.html).

Any objections?

**Comment by bluss** [comment]
- I think we can do most productive benchmarking without real blackbox, stable benchmarks would be a win
- criterion's compile time has in the past been long, and I've avoided it for that reason. How is it now?

**Comment by jturner314** [comment]
> I think we can do most productive benchmarking without real blackbox, stable benchmarks would be a win

We can probably conditionally enable `real_blackbox` only on nightly and do without it on stable.

> criterion's compile time has in the past been long, and I've avoided it for that reason. How is it now?

I just tried adding `criterion` as a dependency and running `cargo build --release`. Without `criterion`: 17s; with `criterion`: 220s. In debug mode (`cargo build`): without `criterion`: 17s, with `criterion`: 92s. So, it does add a lot to the compile time.

Personally, I don't mind the extra compile time because `criterion` needs to be built only once (until I call `cargo clean` or upgrade the compiler). I suppose it would slow down CI, though.

**Comment by bluss** [comment]
On a positive note, I want to design my crates to have fast build times. Not that it's always obvious how to do that...

**Comment by bluss** [comment]
On a positive note, I want to design my crates to have fast build times. Not that it's always obvious how to do that...
