### ISSUE TITLE
Can't get numpy documentation locally

### ISSUE THREAD

**Issue by dineshadepu** [rust-ndarray/ndarray#602]
Hi,

I tried building docs locally using 

``` cargo doc --open ```

When I am trying to acces the doc module to look at numpy manual, it says the file is moved. In the main `lib` file I can't see the `doc` module too. 

I am using ubuntu 16.

**Comment by jturner314** [comment]
Yeah, the `doc` module and `serde`/`rayon` functionality are disabled by default. Will you please try this?

```sh
cargo doc --features=docs --open
```

**Comment by dineshadepu** [comment]
Yeah, it works with the above command. Thank you. Closing it.
