### ISSUE TITLE
Interopable traits for matrix multiplication?

### ISSUE THREAD

**Issue by pmarks** [rust-ndarray/ndarray#624]
I've been working on 'generic' matrix routines for large-scale SVD of (typically sparse) matrices
(e.g. http://www.math.uri.edu/~jbaglama/papers/paper14.pdf and https://arxiv.org/abs/0909.4061)

Ideally the algorithm is written in terms of matrix multiplications of a dense ndarray matrices into arbitrary data matrices (which could be ndarray::ArrayBase, sprs::CsMat, or in some special representation defined in another crate). We'd like to write:
```rust
fn svd<T>(mat: &T, k: usize) -> Array2<...>
where 
   T: Dot<ArrayBase<...>>
   ArrayBase<...>: Dot<T> {
    ...
    let blah = mat.dot(ndarray2_a);
    ...
    let blah2 = ndarray2_b.dot(mat);
    ...
}
```

Unfortunately the orphan rules prevent us from implementing `impl<...> Dot<sprs::CsMat<...>> for ArrayBase<...>` inside the `sprs` crate. 

The best solution I can come up is to introduce an `LDot` trait as follows:

```rust

/// Left hand side multiplication. `obj.ldot(other)` corresponds to the mathematical operation `other * obj`
/// This trait is required to allow `ndarray::Array` and sparse matrix types to interoperate generically.
pub trait LDot<Lhs> {
    type Output;

    /// compute the dot-product `lhs * self`
    fn ldot(&self, lhs: &Lhs) -> Self::Output;
}

/// Blanket impl for convenience
impl<Lhs,Rhs> LDot<Lhs> for Rhs
where
    Lhs: Dot<Rhs>
{
    type Output = Lhs::Output;

    fn ldot(&self, lhs: &Lhs) -> Self::Output {
        Dot::dot(lhs, self)
    }
}
```

This lets other crates define new matrix types that can interoperate with `ndarray` pretty smoothly. We just need to a `T: LDot<ArrayBase<...>>` to the first example and change the appropriate method calls. Thoughts?  I can make PR with this trait easily.  Are there other option for how to solve this problem?

Addendum: solutions that involve the `svd` method taking the transpose of `mat` run into the lack of GATs pretty quickly.

**Comment by SuperFluffy** [comment]
If you aim to implement a new trait anyways, you can keep that in your library and there is no need to add a new trait to ndarray.

I would probably investigate the following two options and note a 3rd observation:

1) Try and see how far you can get with implementing the `Dot` trait of `ndarray` on a newtype wrapping `ArrayBase`. This is usually the recommended method in rust when trying to implement external traits for external types.
2) If you choose to implement a new trait such as `LDot`, there is no need to make it part of ndarray.
3) Be careful in how you use these matrix multiplication methods. Some of these methods are allocating. Given your example above, that's definitely the case. If you aim for maximum performance and repeated application of the same method (I found that that was often the case with operations like SVD), then you want to define some structure/scratch space holding the result of your products.

So a better solution would be to not define a function `svd` that does all the magic, including the said allocations, but to define a struct with all the necessary objects, and then define a method on that struct that takes some matrix you want to factorize. You can then still define a one-off utility function that is implemented in terms of that struct. I can show you some examples, if you want.


I am not a maintainer of ndarray myself, so I submit to their opionion, but right now I fail to see how your implementation of `svd` for sparse matrices requires the introduction of a new trait that helps 3rd parties in defining new matrix types that interact with ndarray.

It strikes me as if the surface area of such an extension is too large.

**Comment by pmarks** [comment]
@SuperFluffy thanks, I don't think I had internalized the newtype trick, but it makes perfect sense. The dependency structure I want to looks something like this:
```
algos --->  ndarray
            ^    ^
            |    |
   sprs -----    |
         sqz------
```

where `algos` has the generic `fn svd()` and `sprs` and `sqz` define various sparse matrix types that I might want to use with `svd()`.  Then I will have a client crate that constructs a `sprs::CsMat` or `sqz::Mat` with the appropriate impls and passes that data matrix to `algos::svd()`. So the problem is where to put the newtype wrapper of `ArrayBase`? If I put the newtype in `sprs` or `sqz` then it can't be reused in the other.

Re the allocations: totally - even the dot() method must allocate, so my generic impls end up allocating more than they need to internally. I think I've seen some discussion of a `dot_into()` method that would let the caller provide an output matrix. That would be a nice extension. In my case the output arrays are very small compared to the data matrix so I'm not anticipating the allocation time being small compared to the actual matrix multiply.

**Comment by jturner314** [comment]
I think it should be possible to add a trait to `sprs`, like this:

```rust
// within the `sprs` crate

use ndarray::{linalg::Dot, ArrayBase, Data, Dimension, Ix2};

pub trait Dot2<Rhs> {
    type Output;
    fn dot(&self, rhs: &Rhs) -> Self::Output;
}

impl<T, S, D> Dot2<T> for ArrayBase<S, D>
where
    S: Data,
    D: Dimension,
    ArrayBase<S, D>: Dot<T>,
{
    type Output = <ArrayBase<S, D> as Dot<T>>::Output;

    fn dot(&self, rhs: &T) -> Self::Output {
        Dot::dot(self, rhs)
    }
}

impl<N, I, IptrStorage, IndStorage, DataStorage, S>
    Dot2<CsMatBase<N, I, IptrStorage, IndStorage, DataStorage>> for ArrayBase<S, Ix2>
where
    S: Data<Elem = N>,
{
    type Output = CsMatBase<N, I, IptrStorage, IndStorage, DataStorage>;

    fn dot(&self, _rhs: &CsMatBase<N, I, IptrStorage, IndStorage, DataStorage>) -> Self::Output {
        // ...
    }
}

impl<N, I, IptrStorage, IndStorage, DataStorage, S> Dot2<ArrayBase<S, Ix2>>
    for CsMatBase<N, I, IptrStorage, IndStorage, DataStorage>
where
    S: Data<Elem = N>,
{
    type Output = CsMatBase<N, I, IptrStorage, IndStorage, DataStorage>;

    fn dot(&self, _rhs: &ArrayBase<S, Ix2>) -> Self::Output {
        // ...
    }
}
```

Then, use `sprs::Dot2` as the constraint in `algos`.

If you don't mind using nightly, it's possible to implement `ndarray`'s `Dot` trait within `sprs` using the [`re_rebalance_coherence` feature](https://doc.rust-lang.org/unstable-book/language-features/re-rebalance-coherence.html):

```rust
// within the `sprs` crate

#![feature(re_rebalance_coherence)]

use ndarray::{linalg::Dot, ArrayBase, Data, Ix2};

impl<N, I, IptrStorage, IndStorage, DataStorage, S>
    Dot<CsMatBase<N, I, IptrStorage, IndStorage, DataStorage>> for ArrayBase<S, Ix2>
where
    S: Data<Elem = N>,
{
    type Output = CsMatBase<N, I, IptrStorage, IndStorage, DataStorage>;

    fn dot(&self, rhs: &CsMatBase<N, I, IptrStorage, IndStorage, DataStorage>) -> Self::Output {
        // ...
    }
}

impl<N, I, IptrStorage, IndStorage, DataStorage, S> Dot<ArrayBase<S, Ix2>>
    for CsMatBase<N, I, IptrStorage, IndStorage, DataStorage>
where
    S: Data<Elem = N>,
{
    type Output = CsMatBase<N, I, IptrStorage, IndStorage, DataStorage>;

    fn dot(&self, rhs: &ArrayBase<S, Ix2>) -> Self::Output {
        // ...
    }
}
```

Does either of those options work for you?

**Comment by pmarks** [comment]
@jturner314 thanks! Yes, I thin the re-rebalancing coherence is the ticket.  Looks like should get stabilized in the not too distant future, so I'll work with that on nightly for now.

**Comment by jturner314** [comment]
@pmarks FYI, `re_rebalance_coherence` is now stable (Rust 1.41).
