### ISSUE TITLE
Add bitflags for memory layout

### ISSUE THREAD

**Issue by bluss** [rust-ndarray/ndarray#63]
We probably want to mimic numpy here by using a bitfield for keeping track of memory layout. c order, f order (both possible at the same time), as well as neither order. Maybe some blas-related property is relevant down the line. May even be a `Cell` field to update it on the fly? (This makes the type `!Sync` which we don't want..)

**Comment by vbarrielle** [comment]
Should it be bitflags? Looks like it can be computed on the fly from the strides.

**Comment by bluss** [comment]
This information is needed very often (every as_slice, every arithmetic operation), so we need to look if there is anything to be gained.

**Comment by vbarrielle** [comment]
Ok I didn't realize it was needed so often. So in that case it probably should be computed when strides are assigned to the array. As far as I can tell there's no way to change the strides of an existing array so I don't think the flag could get out-of-sync wrt the strides.

**Comment by bluss** [comment]
A note for any implementors is that strides change in islice, isubview.

**Comment by nilgoyette** [comment]
Closing this issue

- This is either already added, or the maintainers decided to use `is_standard_layout` (and some other methods) instead, or a mix of both.

Feel free to re-open this issue if I'm wrong.
