### ISSUE TITLE
ArcArray1

### ISSUE THREAD

**Issue by max-sixty** [rust-ndarray/ndarray#661]
There are some references to [`RcArray1` & `RcArray2`](https://github.com/rust-ndarray/ndarray/blob/master/serialization-tests/tests/serialize.rs#L29), causing some warnings. I was planning to put in a PR to move these to ArcArray, but ArcArray1 doesn't exist.

Should we create them? Or move specializations up a level?

**Comment by LukeMathWalker** [comment]
In the end, it's syntactic sugar and I think we should keep them (if nothing else, for consistency with `Array1`, `ArrayView1`, etc.). What do you mean by moving specializations up a level?

**Comment by max-sixty** [comment]
Should we create `ArcArray1` & `ArcArray2`? Currently we only have a deprecated `RcArray1` & `RcArray2`

**Comment by LukeMathWalker** [comment]
Yes, I think we should.

**Comment by max-sixty** [comment]
@alex197ohm if you're looking for a good issue to begin with, this could be interesting
