### ISSUE TITLE
0.13 release

### ISSUE THREAD

**Issue by rth** [rust-ndarray/ndarray#670]
The last release (0.12.1) was 8 month ago and in looks like a lot of development has happened since. 

I was wondering if there were plans to make a new release in the near future? Couldn't find any existing issues or milestones about it.

Personally, I am interested in using https://github.com/rust-ndarray/ndarray/pull/581 for approximate equality tests, but it's not part of any release yet..

Thanks for your great work on ndarray!

**Comment by LukeMathWalker** [comment]
I'd say it makes sense to start thinking about a new release. 
There are several PRs in flight at the moment, but I don't see any major new functionality piece being worked on. Could we perhaps set a date in the nearby future to wrap up the existing work and review what has been done before releasing? (Given that we have more than one breaking change already in master)

End of August/beginning of September sounds reasonable to me. What do you think @jturner314?

**Comment by jturner314** [comment]
Sure, that seems reasonable to me. How about tentatively Sep. 1?

At a minimum, we should merge the PRs labeled [`bug`](https://github.com/rust-ndarray/ndarray/pulls?q=is%3Apr+is%3Aopen+label%3Abug) and PR #633 before releasing 0.13, and we should decide which of the open [`breaking-change`](https://github.com/rust-ndarray/ndarray/pulls?q=is%3Apr+is%3Aopen+label%3Abreaking-change) PRs to merge. #627 is postponed. It would be good to finish up #626 and merge it. PR #570 would be nice, but could wait until 0.14 (and I plan to add support for ellipses while slicing, which will require further breaking changes, so it would be nice to do all the breaking changes at once). All the other open PRs can be part of 0.13.1 if necessary.

**Comment by bluss** [comment]
I would be excited to finally have matrixmultiply 0.2 improvements in the user's hands.

**Comment by LukeMathWalker** [comment]
Let's do a checkpoint, just to see where we are at.

> At a minimum, we should merge the PRs labeled [`bug`](https://github.com/rust-ndarray/ndarray/pulls?q=is%3Apr+is%3Aopen+label%3Abug) and PR #633 before releasing 0.13, and we should decide which of the open [`breaking-change`](https://github.com/rust-ndarray/ndarray/pulls?q=is%3Apr+is%3Aopen+label%3Abreaking-change) PRs to merge. #627 is postponed. It would be good to finish up #626 and merge it. PR #570 would be nice, but could wait until 0.14 (and I plan to add support for ellipses while slicing, which will require further breaking changes, so it would be nice to do all the breaking changes at once). All the other open PRs can be part of 0.13.1 if necessary.

All PRs labeled [`bug`](https://github.com/rust-ndarray/ndarray/pulls?q=is%3Apr+is%3Aopen+label%3Abug) have been closed.
#633 is mostly waiting for us to reach consensus on what we want the format to look like.
Do we want to wait for #683 and #626? #683 seems to be moving quite fast now that @bluss is on it and #626 would probably deliver a substantial amount of value to users.

**Comment by bluss** [comment]
I'd like to resolve #705 for 0.13, even though it could be resolved in 0.13.1 too. Increasing the limit of # elements shown by default would be good.

**Comment by bluss** [comment]
When changed formatting overflow limits - #713 - is merged I don't have any blockers for the release anymore.

**Comment by jturner314** [comment]
In addition to #713, the only other thing is deciding on #692 since it's a breaking change.

**Comment by bluss** [comment]
- ndarray 0.13 is now out! So many changes everyone has worked on :rocket: 
- ndarray-rand 0.11.0 also bumped up to ndarray 0.13.
- ndarray-parallel 0.9.1 has been marked deprecated in crates.io and in docs (and is *not* updated to use the new version).

I suggest we try to avoid merning breaking changes for a little while, so that we can focus on 0.13.1. That way the fixes and improvements we do merge more quickly become useful for everyone.

Feel free to speak for the project and make blog posts if you want. I guess we can at least share the changelog on the various forums :slightly_smiling_face:

**Comment by bluss** [comment]
Thanks all that contributed so much :fire:  and I'm sorry it has taken a long time to make the release. 

I've written a brief announcement on the user forum https://users.rust-lang.org/t/ndarray-0-13-released/32864 that mentions just some of the improvements.

**Comment by LukeMathWalker** [comment]
Added a [release announcement](https://www.reddit.com/r/rust/comments/d8cb8x/ndarray_013_released/) on `r/rust` as well, mostly following yours bluss :+1:
