### ISSUE TITLE
Good blog post on numpy vs ndarray

### ISSUE THREAD

**Issue by max-sixty** [rust-ndarray/ndarray#678]
https://ngoldbaum.github.io/posts/python-vs-rust-nn/

Issues I extracted (comment if more):
- rand compat. Fixed the specific issue with https://github.com/rust-ndarray/ndarray/pull/659, and the library dependency issues with https://github.com/rust-ndarray/ndarray/pull/663
- matrix-multiplication with >2D arrays https://github.com/rust-ndarray/ndarray/issues/16
- ease tuple / slice conversions?

Thanks @ngoldbaum

**Comment by bluss** [comment]
Thanks. I hope const generics will help us with tuple/slice conversion. I'll archive this issue for now.

We have existing issue #169 too for rand, #16 for the matrix multiplication.
