### ISSUE TITLE
Change uninitialized to return an array of MaybeUninit

### ISSUE THREAD

**Issue by jturner314** [rust-ndarray/ndarray#685]
The `.uninitialized()` method on `ArrayBase` has some issues. For example, `Array1::<bool>::uninitialized(2)` is undefined behavior.

Rust 1.36 added `std::mem::MaybeUninit` for safer handling of uninitialized data. We should replace the existing `.uninitialized()` method on `ArrayBase` with one that returns an array of `MaybeUninit` instances. We then need to add the necessary methods to cleanly work with arrays like this (e.g. an array-level equivalent of `assume_init`).

**Comment by bluss** [comment]
Internally I'd kind of just like a `Zip` with ndproducers that would give out raw pointers to the elements (so that we avoid references and iteration is sound). That way we can use uninitialized or similar correctly using some raw pointer code, at least.

**Comment by bluss** [comment]
I'm not sure the recipe in the title of this issue is what we should do - there might be better ways to do it, for example to provide raw pointer traversals

**Comment by bluss** [comment]
Can we explain why `Array1::<bool>::uninitialized(2)` is UB?  What's the difference to `Vec::<bool>::with_capacity(2)`?

**Comment by bluss** [comment]
Internal implementation of this is added in #797, that's a start.
