### ISSUE TITLE
Nonexistent distinction between .t() and .reversed_axes() in the docs.

### ISSUE THREAD

**Issue by axil** [rust-ndarray/ndarray#695]
The [docs](https://docs.rs/ndarray/0.12.1/ndarray/doc/ndarray_for_numpy_users/index.html) says
> transpose of array a (view for `.t()` or by-move for `.reversed_axes()`)

But it looks as though in current version of ndarray there's no distinction between those two:

https://github.com/rust-ndarray/ndarray/blob/ea82bf433d01017b6bcee01896617f36404e3bfd/src/impl_methods.rs#L1684-L1694

**Comment by bluss** [comment]
They have different signature and when you call them on an Array you'll notice their different behaviour.

Signatures from docs:
```rust
pub fn reversed_axes(self) -> ArrayBase<S, D> { ... }
pub fn t(&self) -> ArrayView<A, D> { ... }
```

**Comment by axil** [comment]
Oh, ok, thanks. The `reversed_axes` moves the array itself. I thought that it meant moving values inside the array (keeping the original layout). It might probably be worthwhile to mention that all the values are kept in place in both versions (not an in-place transposition).
