### ISSUE TITLE
ndarray build time / compile time

### ISSUE THREAD

**Issue by bluss** [rust-ndarray/ndarray#723]
I just wanted to share a neat graph. (This is a new feature in cargo - run with `-Ztimings` and it outputs this!)

[HTML build time for ndarray + deps](http://gistpreview.github.io/?f57a987580d861d1c84ca162cae0b0ad)  I used a rayon benchmark as testcase, so it's a release compile, and my laptop struggles a bit, so it's slowish :-)

You can set the min unit time to 1 second to get an easier to overview time chart of the build.

Here we can look at how the build time of the crate is broken down, obviously we only decide about the direct deps and not transitive deps of any crates we don't control.

**Comment by bluss** [comment]
Also, look at that sweet pipelining (when cargo starts building the next crate in the chain before the codegen of the dependency is finished).

**Comment by max-sixty** [comment]
Awesome chart. Would it be worth looking at the non-dev dependencies only too? e.g. I see quickcheck uses up a bunch of time there

**Comment by jturner314** [comment]
Very cool. This feature is really helpful for figuring out how to reduce build times. I noticed that it also shows the edges of the dependency graph associated with a crate if you hover over that crate. I think it's interesting that the vast majority of the time spent compiling `ndarray` itself is in things other than code generation; it would be helpful to know more specifically where that time is spent.

**Comment by bluss** [comment]
Acrichto wrote about this today too https://internals.rust-lang.org/t/exploring-crate-graph-build-times-with-cargo-build-ztimings/10975?u=dtolnay
