### ISSUE TITLE
Zero axis lengths?

### ISSUE THREAD

**Issue by nilgoyette** [rust-ndarray/ndarray#731]
While working on ndarray-stats, I discovered that it's possible to have "zero axis lengths".

    let arr = Array2::zeros((0, 10));

There's some issues #579, #693 and some panic information about them in the doc, for example `fn default`: `Panics if the product of non-zero axis lengths overflows isize.` but I can't find any useful information on them. It seems to me that they're overly-complex empty arrays and that you can do nothing useful with them. I'm probably wrong?

I think it's right to say that nobody will create such an array deliberately so I guess one of the method in ArrayBase can create one? Can someonie explain me why they exist? What's their use-cases?

**Comment by bluss** [comment]
I think just like zero-length Vecs and slices appear in various situations, we have these.  ArrayBase uses the same model for axes, shapes and strides for all its storage types, so since zero-width slices (views) are naturally occurring when slicing and splitting, we can see such shapes for owned arrays too.

**Comment by bluss** [comment]
Just briefly, there are many ways to use tables of numbers in this world, but let's say we have a model with data like this:

```
+--------+--------+-------+
| weight | length | width |
+--------+--------+-------+
|    7.2 |     40 |    65 |
|      8 |     30 |   180 |
+--------+--------+-------+
```

We can store it in a n × 3 table for our n data points.

It's a valid situation in the program that we can have 0 data points at any given time. Then we have a matrix of 0 × 3 values.

```
+--------+--------+-------+
| weight | length | width |
+--------+--------+-------+
```

**Comment by nilgoyette** [comment]
Yeah, ok, that makes sense. I had trouble imagining it for 2D arrays, but I'm perfectly ok with empty 1D array.

Thank you for taking the time to answer.
