### ISSUE TITLE
Wrapping slice (as in ring buffer)

### ISSUE THREAD

**Issue by 0x7CFE** [rust-ndarray/ndarray#745]
Is there a way to produce a wrapping slice or slice-like behavior, that resembles the way how a ring buffer works?

Suppose I have an array `[1, 2, 3, 4, 5, 6]`. I'd like to be able to slice into it like `[-2, 2]` to yield `[5, 6, 1, 2]`.

Obviously, it would be impossible to gain a single contiguous memory region, but I do not need that. It would be fine to yield one element/reference at a time.

P.S.: I understand that similar behavior could be achieved by using chaining of `-2 ..` and `..2` iterators, but maybe there exists a more idiomatic solution?

**Comment by bluss** [comment]
Arrays and views only allow one single strided chunk, not multiple different, so our model does not allow this at this point.
