### ISSUE TITLE
Convert NdIndex to 1D array or similar

### ISSUE THREAD

**Issue by HactarCE** [rust-ndarray/ndarray#748]
I would like to write a function that takes an `NdIndex` but then does some math on the numbers before indexing into an array. This function must be general over any number of dimensions. Is there any way to turn an `NdIndex` into a 1D array, or otherwise take a vector with length according to a type parameter `D: Dimension`?

**Comment by jturner314** [comment]
The best way to operate generically over the number of dimensions is to use the types that implement `Dimension` (i.e. `Ix0`, `Ix1`, ..., `IxDyn`). Here's an example:

```rust
use ndarray::prelude::*;
use ndarray::Data;

fn index_with_elems_divided_by_two<S, D>(array: &ArrayBase<S, D>, mut index: D) -> &S::Elem
where
    S: Data,
    D: Dimension,
{
    for i in 0..index.ndim() {
        index[i] /= 2;
    }
    &array[index]
}
```

If you want to allow a wider range of inputs for `index` (e.g. tuples and fixed-size arrays), you can use the `IntoDimension` trait, like this:

```rust
use ndarray::prelude::*;
use ndarray::{Data, IntoDimension};

fn index_with_elems_divided_by_two<S, D, I>(array: &ArrayBase<S, D>, index: I) -> &S::Elem
where
    S: Data,
    D: Dimension,
    I: IntoDimension<Dim = D>,
{
    let mut index: D = index.into_dimension();
    for i in 0..index.ndim() {
        index[i] /= 2;
    }
    &array[index]
}
```

Does that answer your question?

**Comment by HactarCE** [comment]
Yes I believe it does, thank you very much!
