### ISSUE TITLE
Is it possible to collect a Zip into Array?

### ISSUE THREAD

**Issue by xiaoniu-578fa6bff964d005** [rust-ndarray/ndarray#755]
Currently if we need to do elementwise operation on array, we can create a result array, and wrap it together with parameters arrays in `Zip` and use `apply` to assign the result. However, since `Zip` have the shape information, can we add a helper function to allocate a result array with correct shape, so that we don't need to create the result array manually?

**Comment by bluss** [comment]
Seems like a reasonable feature request long-term.

**Comment by bluss** [comment]
This seems to be enough to implement this feature on Zip with some limitations (Copy-only elements because we miss handling of partially filled arrays with elements that are uninit or need drop).

```rust
            /// Apply function and collect the results into a new array.
            pub fn apply_collect<R>(self, mut f: impl FnMut($($p::Item,)* ) -> R) -> Array<R, D>
                where R: Copy,
            {
                unsafe {
                    let mut output = Array::uninitialized(self.dimension.clone());
                    self.and(output.raw_view_mut())
                        .apply(move |$($p, )* output_| {
                                std::ptr::write(output_, f($($p ),*));
                        });
                    output
                }
            }


```
