### ISSUE TITLE
Source code page in documentation does not show up correctly

### ISSUE THREAD

**Issue by tolvanea** [rust-ndarray/ndarray#759]
If I go to the documentation, for example
https://docs.rs/ndarray/0.12.1/ndarray/struct.ArrayBase.html
and clicks source code [src] of some method, then the link directs to a white page that contains only highlighted line numbers but no visible source code. If I scroll down, source code is there, but at the bottom of the page. For example
https://docs.rs/ndarray/0.12.1/src/ndarray/lib.rs.html#1026-1039

This behaviour has not happened with other rust documentations before, so I guess this may be fixable by ndarray side. It is still quite weird that auto-generated documentation does not show up properly.

Tested web browsers: Firefox / Chromium on Ubuntu 19.10.

**Comment by bluss** [comment]
It was a bug in rustdoc, and it's fixed (see the ndarray 0.13 docs). It would be a docs.rs issue to update the old documentation, but I don't think it will happen.
