### ISSUE TITLE
Mutable slices must be in variable

### ISSUE THREAD

**Issue by nilgoyette** [rust-ndarray/ndarray#760]
I sometime need to take a slice and modify it, like I would do in NumPy.

    # NumPy, yay, it works
    data[:, 0] *= 2.0

    // Rust, error.
    data.column_mut(0) *= 2.0;
    ^^^^^^^^^^^^^^^^^^ invalid expression for left-hand side

    // Rust, it works
    let first_column = data.column_mut(0);
    first_column *= 2.0;

All slice modifications (row, column and slice(s![])) force me to put the `ArrayView` in a variable before and I don't understand why. How is this invalid if it's valid in a variable?

**Comment by jturner314** [comment]
This is a limitation of the Rust language. For [compound assignment expressions](https://doc.rust-lang.org/stable/reference/expressions/operator-expr.html#compound-assignment-expressions) (and assignment expressions), the expression on the left side of the `=` must be a [place expression](https://doc.rust-lang.org/stable/reference/expressions.html#place-expressions-and-value-expressions). Place expressions are "paths which refer to local variables, static variables, dereferences (`*expr`), array indexing expressions (`expr[expr]`), field references (`expr.f`) and parenthesized place expressions. All other expressions are value expressions."

These are a few workarounds for this particular case:

* assign to a variable, as in your example above
* import the `MulAssign` trait with `use std::ops::MulAssign;` and then call `data.column_mut(0).mul_assign(2.0)`
* use something like the `map_inplace` method, e.g. `data.column_mut(0).map_inplace(|x| x *= 2.0)`
* use this somewhat bizarre workaround to turn the left side into a place expression: `*&mut data.column_mut(0) *= 2.0`

**Comment by nilgoyette** [comment]
TIL. Thank you for the explanation and workarounds.

**Comment by bluss** [comment]
I'd like that we gather these kinds of lang concerns and bring them to the community for possibly improving Rust in the long term. Other operator limitations also apply I think, including indexing.

**Comment by bluss** [comment]
Another thing that comes to mind is += used on interior mutable paths to values.
