### ISSUE TITLE
Should `ArrayBase::all_close` be un-deprecated?

### ISSUE THREAD

**Issue by tolvanea** [rust-ndarray/ndarray#763]
Apparently ArrayBase::all_close() has been deprecated in favor of approx crate and feature. 
I think this new method brings unnecessary complications to the workflow i.e. extra crate must be included and feature must be enabled by hand in Cargo.toml. So my question is: Is the deprecation really worth the benefits it brings? Or why is it deprecated at all?

**Comment by bluss** [comment]
For now, using approx is the solution we have chosen.

Can we propose a remedy? Adding inherent methods with the same names - `abs_diff_eq` so that one doesn't have to use the approx traits, just enable the feature?
