### ISSUE TITLE
Bump blas to 0.4.0

### ISSUE THREAD

**Issue by djugei** [rust-ndarray/ndarray#765]
ndarray-linalg uses 0.4.0 too

**Comment by djugei** [comment]
thanks @hameerabbasi

**Comment by bluss** [comment]
Temporary re-open, this should be reapplied for the 0.14 release

**Comment by hameerabbasi** [comment]
Should I submit another PR or would you prefer to revert the revert?

**Comment by bluss** [comment]
I think we can just revert it again
