### ISSUE TITLE
Development on macOS

### ISSUE THREAD

**Issue by hameerabbasi** [rust-ndarray/ndarray#769]
When running the BLAS tests on macOS, I run into the following linking error:

```
error: linking with `cc` failed: exit code: 1
    ...
= note: ld: library not found for -lgfortran
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I've tried using `CC=gcc-9 CXX=g++-9` to no avail, it still invokes `cc` and not `gcc`.

I've also modified `LD_LIBRARY_PATH` to include `libgfortran.a` but it shows the same error.

Any ideas on what to do next? This happens even on `master`.

**Comment by hameerabbasi** [comment]
Thanks to the user `pentree` on Discord, I got a bit further by replacing `LD_LIBRARY_PATH` with `LIBRARY_PATH`, but now `-lopenblas` isn't found.

**Comment by hameerabbasi** [comment]
In case it helps anyone else, I set `LIBRARY_PATH=${PATH_OF_libgfortran.a:PATH_OF_libopenblas.a}` and it worked.

**Comment by schell** [comment]
I'm hitting this as well, surely there's a way to fix this without having to hand locate these libs?
