### ISSUE TITLE
Ffill for NaNs

### ISSUE THREAD

**Issue by CharlieBickerton** [rust-ndarray/ndarray#773]
I'm using ndarray for a project that I'm currently working on. I required to replace NaNs in a 1d array and I've recreated a similar function to [pandas ffill](https://pandas.pydata.org/pandas-docs/stable/reference/api/pandas.DataFrame.ffill.html).

I can share the code if this is something that might be helpful for ndarray?

**Comment by nilgoyette** [comment]
Closing this issue because it is too specific. It belongs in the `ndarray` ecosystem (although I'm not sure where), not in `ndarray`.
