### ISSUE TITLE
split_at for references?

### ISSUE THREAD

**Issue by xldenis** [rust-ndarray/ndarray#784]
It seems like it should be possible to have `split_at` on mutable references for `ArrayViewMut`.

My usecase is to recursively split a view into quadrants on which I'd like to perform multiple updates (sequentially of course). Currently I can turn a `&mut ArrayViewMut -> (&mut ArrayViewMut, &mut ArrayViewMut)` by using `axis_chunks_iter_mut` but that seems rather sub-optimal.

**Comment by jturner314** [comment]
Does `ArrayViewMut`'s [`split_at`](https://docs.rs/ndarray/0.13.0/ndarray/type.ArrayViewMut.html#method.split_at) method meet your needs? Note that if all you have is a `&mut ArrayViewMut`, you can turn it into an `ArrayViewMut` by calling `.view_mut()`.

**Comment by xldenis** [comment]
aha! `view_mut` does the trick it seems!
