### ISSUE TITLE
Equivalent of numpy.all and numpy.any (truth value testing)

### ISSUE THREAD

**Issue by espdev** [rust-ndarray/ndarray#786]
It would be great to have `numpy.all` and `numpy.any` equivalent functions/methods for bool type arrays in rust-ndarray.

An example of use case:
```rust
let x = array![0.1, 0.5, 0.2, 1.4];

assert!(x.mapv(|v| v > 0.0).all(), "all values in the array must be greater than zero")
```

**Comment by espdev** [comment]
It seems, we can use like methods from `Iterator` through `iter()` in most cases.

**Comment by bluss** [comment]
For now, there is `Zip::all`
