### ISSUE TITLE
Question about swap axes

### ISSUE THREAD

**Issue by xd009642** [rust-ndarray/ndarray#791]
https://docs.rs/ndarray/0.13.0/ndarray/struct.ArrayBase.html#method.swap_axes

```
Swap axes ax and bx.

This does not move any data, it just adjusts the array’s dimensions and strides.
```

If this doesn't move any data does that mean that a default row major array becomes column major? If so is there a way to swap axes and retain memory ordering?

**Comment by xd009642** [comment]
Okay it appears that it's no longer continuous in memory as `ArrayBase::as_slice` returned `None`. Is there a nice ergonomic way to do this or should I just copy the data?

**Comment by jturner314** [comment]
`a.swap_axes(0, 1)` on a 2-D array transposes the array by swapping the axis length and stride for axis `0` with the axis length and stride for axis `1`. The data is not moved, so if `a` is a contiguous row-major array, after `a.swap_axes(0, 1)`, it is a contiguous column-major array of the transpose:

```rust
use ndarray::prelude::*;

fn main() {
    let mut a = array![[1, 2, 3], [4, 5, 6]];
    assert!(a.is_standard_layout());
    assert_eq!(a.shape(), &[2, 3]);
    assert_eq!(a.strides(), &[3, 1]);
    assert_eq!(a.as_slice_memory_order(), Some(&[1, 2, 3, 4, 5, 6][..]));
    assert_eq!(a, aview2(&[[1, 2, 3], [4, 5, 6]]));

    a.swap_axes(0, 1);
    assert!(!a.is_standard_layout());
    assert_eq!(a.shape(), &[3, 2]);
    assert_eq!(a.strides(), &[1, 3]);
    assert_eq!(a.as_slice_memory_order(), Some(&[1, 2, 3, 4, 5, 6][..]));
    assert_eq!(a, aview2(&[[1, 4], [2, 5], [3, 6]]));
}
```

Given a row-major array, if you want a row-major array containing its transpose, the simplest way is to create a new row-major array and then assign the transpose to it:

```rust
use ndarray::prelude::*;

fn main() {
    let a = array![[1, 2, 3], [4, 5, 6]];
    let a_t = a.t();
    let mut a_t_owned = Array2::zeros(a_t.raw_dim());
    a_t_owned.assign(&a_t);
    assert_eq!(a_t_owned, aview2(&[[1, 4], [2, 5], [3, 6]]));
    assert_eq!(a_t_owned.strides(), &[2, 1]);
}
```

Does that answer your question?

**Comment by xd009642** [comment]
Yeah and it does end up being the solution I came to so nice to know I have the recommended solution :+1:

**Comment by xd009642** [comment]
Close #791
