### ISSUE TITLE
Are there any matrix-free solvers?

### ISSUE THREAD

**Issue by medakk** [rust-ndarray/ndarray#793]
Hi! Does ndarray support any matrix-free solvers?

**Comment by bluss** [comment]
What is a matrix-free solver? The answer is probably no, ndarray does not implement much linear algebra related functionality.

**Comment by medakk** [comment]
In matrix-free solver, instead of `x = solve(A, b)`, we run `x = solve(f, b)`, where is a function `f(y) = Ay` that can evaluate the product of A and any vector. This is useful in some situations where we don't need to store the entire matrix. https://en.wikipedia.org/wiki/Matrix-free_methods

**Comment by bluss** [comment]
Thanks for elaborating on it! The repo ndarray-linalg would be the place to propose introducing this, I think

**Comment by medakk** [comment]
Okay, thanks! I've created an issue [here](https://github.com/rust-ndarray/ndarray-linalg/issues/190)
