### ISSUE TITLE
Is it advised to use `Data` and `RawData` in client's code?

### ISSUE THREAD

**Issue by pkubik** [rust-ndarray/ndarray#801]
I'd like to implement some generic functions on arrays for my image processing library. E.g.:
```
fn crop<S: Data + RawData>(array: &ArrayBase<S, Ix2>, _roi: Rectangle) -> ArrayView2<<S as RawData>::Elem> {
    // NOT REALLY IMPORTANT (roi used to compute the actual slice)
    array.slice(s![0..10, 0..10])
}
```
In the example I'm cropping an `Array[View]2` using a custom `Rectangle` class and returning a view for the resulting slice. It works, but the docs advise against the use of `RawData` trait and its subtypes.

Is it acceptable use or am I risking some breaking change after some future update? Any idea how to implement my function without those traits then?

**Comment by bluss** [comment]
You need Data for this method, so best just use it (RawData is implied by Data).

In the long run there is a minor risk for breaking changes on almost anything, because we need to traitify ndarray (stop using ArrayBase as a type).

**Comment by pkubik** [comment]
Ok, then. Although I must give it a second thought. Not sure if it wouldn't be more idiomatic to accept only views in most of my functions, since user can always call `array.view()`. Also I would avoid providing `xxx_mut` version of every function to produce a mutable view.

Thank you.

**Comment by bluss** [comment]
An argument conversion trait could be a good thing, then you have only one place where you define it. We *don't* have the perfect conversion traits in the crate, but we have AsArray, and I've often contemplated removing it. If you'd use it or invent a better way/shape of that, feedback is appreciated.

**Comment by bluss** [comment]
If you want to be super generic,  think the way to go is unfortunately using slice_move, then you can slice an Array, ArrayView, RawArrayView etc.
