### ISSUE TITLE
Remove Array::uninitialized()

### ISSUE THREAD

**Issue by bluss** [rust-ndarray/ndarray#804]
It now has a replacement. See previous issue #685 

If 0.14.0 comes quickly after 0.13.1, probably start with just deprecating the method

**Comment by bluss** [comment]
Possibly put maybe_uninit in its place (rename it)

**Comment by bluss** [comment]
uninitialized is hard to use correctly. I haven't removed it yet because I think I have managed to put it on sound ground - it *is technically possible* to use it correctly. See issue #804  and issue #876 (we have just completed removing all internal usage of this method).

Unfortunately `ArrayBase::uninitialized`:

1. Has some usage by actual users - it's a basically popular and easy to use (github code search confirms)
2. This usage is from casual inspection almost always technically incorrect


The conclusion is that deprecation will have impact on users, but we need to do it, and need to make `maybe_uninit` easy to use.

**Comment by xd009642** [comment]
Now I'm wondering how incorrect my usage in ndarray-vision is :sweat_smile:

**Comment by bluss** [comment]
`uninitialized` was added before stronger rules crystallized. Many had the thought that `let x = uninitialized(); *(&mut x) = 1.0;` was correct when the type was copy - however that as also been judged as incorrect, so there are not many easy ways to use it left - short of using the raw views (partly why they were introduced). Yes, your code breaks this rule (as did ours before the next version).

**Comment by bluss** [comment]
See also #796 (A lot of progress has been made on that issue).

**Comment by bluss** [comment]
Deprecated by #902, so this issue is now fixed. But it will be finally removed in the next release.
