### ISSUE TITLE
Implement std::iter::Sum over arrays

### ISSUE THREAD

**Issue by rasa200** [rust-ndarray/ndarray#807]
# Background

In numerical simulations, I sometimes need to sum over many generated `Array1<f64>` that represent vectors in space (e.g. to compute their means). These vectors are naturally generated by some simulated procedure, maybe in parallel. Therefore, I find myself with an iterator that yields `Array1<f64>` and I need the sum of all these vectors. 

# Request
Implement the trait ` std::iter::Sum` for ArrayBase. 

## Example code
I would like for the next code to work. 
```
use ndarray::{array, Array1};
fn main() {
	let samples: u64 = 100;
	let result: Array1<u64> = (0..samples).map(|_| array![1, 2]).sum::<Array1<u64>>() / samples;
	assert_eq!(result, array![1, 2]);
}
```
Currently, it gives me the following message.
```
the trait `std::iter::Sum<ndarray::ArrayBase<ndarray::data_repr::OwnedRepr<{integer}>, ndarray::dimension::dim::Dim<[usize; 1]>>>` is not implemented for `ndarray::ArrayBase<ndarray::data_repr::OwnedRepr<u64>, ndarray::dimension::dim::Dim<[usize; 1]>>`
```

## Current solution
One could use `fold`.
```
use ndarray::{array, Array1};
fn main() {
    let samples: u64 = 100;
    let result: Array1<u64> = (0..samples)
        .map(|_| array![1, 2])
        .fold(array![0, 0], |acc, x| acc + x)
        / samples;
    assert_eq!(result, array![1, 2]);
}
```
Another solution is to build an `Array2` with all my `Array1` instances, but this asks for allocation that I don't need and is less ergonomic.

**Comment by bluss** [comment]
Sounds reasonable. The trait definition is

````rust
pub trait Sum<A = Self> {
    fn sum<I>(iter: I) -> Self
    where
        I: Iterator<Item = A>;
}
```

before starting, look at for which array types this can be implemented and what the corresponding element `A` should be. `Self` is the result of the summation and `A` is the elements of the sequence being summed.

**Comment by rasa200** [comment]
Thank you very much for the quick answer!! 
I will give my first guess for now, sorry if I don't understand the crate well yet.

# Fixed shape
One can implement the trait for arrays with the same shape as a first step. 
Error handling should be just as good as summing this arrays, i.e., for now, panics at runtime. (right?)

# Broadcasting
One would also want to be able to sum with possibly different shapes using broadcasting. This is a complication because one would have to return the... largest shape?

## Example
```rust
let a = array![0, 1];
let b = array![[1, 2], [5, 6]];
assert_eq!(array![[1, 3], [5, 7]], b + &a);
```

In the other hand, the iterator has to have a specific type, so using broadcasting (in the `sum` method for the iterator) can only occur if the shape is dynamic. Something like
```rust
let c = [a.into_dyn(), b.into_dyn()].iter();
```
In this case, the return type is also with a dynamic shape and again, the error should be just as using the fold method, i.e. panicking at run time (?)

# Naive proposal

Using `A = ArrayBase<S, D>` should be okay. 
I am sure I am missing a lot here.

**Comment by bluss** [comment]
We have a minor roadblock, what do we do when the input is an empty iterator? Then it's impossible for us to say what the size of the result should be.

**Comment by bluss** [comment]
Maybe I regret the good first issue, but that's not directed to you or anyone in particular. Feel free to tackle this, though there seems to be design questions to handle.

**Comment by rasa200** [comment]
No problem! Let me try to give an answer. (sorry if I state some obvious things)

# Question
What do we do when the input is an empty iterator?
Is it possible to say what the size of the result will be?

# Answer
Iterators have an associated type, and the result of summing over a type should always be that same type (*more complex implementations of `Add` will be discussed later). Therefore, no matter if the iterator is empty or not, the result is a known type with a known size, at least for numerical primitives. (right?)
Also, the sum over an empty iterator should be the zero element, just as in mathematics.

## Caveats
I had a look at the implementation of [std::iter::Sum](https://doc.rust-lang.org/std/iter/trait.Sum.html) and noticed the following:
1. There are types that (in principle) could implement the trait but they do not, e.g. String. 
2. Instead of asking for a `Zero` trait in the input, they implement the trait `Sum` only for numerical primitives. 

By the first point, I mean that the following code does not work.
```rust
let a = vec!["boo".to_string(), "far".to_string()];
let expected = "boofar".to_string();
let sum = a.into_iter().sum::<String>();
assert_eq!(expected, sum);
```
because `String` does not implement `std::iter::Sum`, because one can add `String + &String`, but not `String + String`. One could argue that an iterator over `String` could be summed over to produce a `String`... but I am sure there are reasons for this.

This takes us to the second point. What are the types that do implement `std::iter::Sum`? 
Only numerical primitives and their `Wrapping` and `&Wrapping` versions. Also a "recursive" definition for (nested) `Option` and `Result` versions. 

# Conclusions
Implementing `Sum` in arrays with numerical primitives should be fine, jus as the `std`. This implies copying the implementation in `std`, which is: use the `zero`, `fold` and `add`. From the `std`, the code (for integer types) looks like this:
```rust
#[$attr]
impl<'a> Sum<&'a $a> for $a {
    fn sum<I: Iterator<Item=&'a Self>>(iter: I) -> Self {
        iter.fold($zero, Add::add)
    }
}
```

# Beyond numerical primitives
Since there is already the dependence on the crate `num-traits`, we could actually go on and implement over data types that implement [num_traits::identities::Zero](https://docs.rs/num-traits/0.2.11/num_traits/identities/trait.Zero.html) and the [std::ops::Add](https://doc.rust-lang.org/std/ops/trait.Add.html) trait. 

The bounds here are a bit more complicated since the result might not be the underlying type of the array but the type in the implementation of `Add`.

Do we want such a general implementation?

**Comment by bluss** [comment]
Add is already implemented.

We don't implement Zero because we don't know what size the array zero should be.

We should have for a zero element *z* that   *z* + a = a and a + *z* = a  but addition is only defined if *z* and *a* have the same shape. For a given type - for example  `Array2<f64>`, the two-dimensional owned array, we can't produce a zero value that works in the right way for all other two dimensional owned arrays. 🙂

**Comment by rasa200** [comment]
Thanks for bearing with me!! Now I get the problem. 

Then, the only thing we could do is to "invent" the `CheckedSum` trait, i.e. return an `Option` instead of `Self`. Something like
```rust
pub trait CheckedSum<A = Self> {
    fn checked_sum<I>(iter: I) -> Option<Self>
    where
        I: Iterator<Item = A>;
}
```

It does not sound too bad to me since the "zero-type" in Rust is `None`... although a bit disappointing. 

If there were two-sided broadcasting, I don't think it would be the solution either: if a user had an iterator yield 2x2 matrices in the form of `Array2<f64>` all the time, then using `sum` "should" also yield a 2x2 matrix (even if the iterator is empty)... or at least that is what I would expect as a user.

I am not particularly asking for the implementation of the `CheckedSum` trait unless you think it is worthy.

PD: A similar scenario comes when dealing with the [std::iter::Product](https://doc.rust-lang.org/std/iter/trait.Product.html) trait ... and the [num_traits::identities::One](https://docs.rs/num-traits/0.2.11/num_traits/identities/trait.One.html) trait.

**Comment by bluss** [comment]
It sound useful to implement `Sum`, if possible, to enable the `.sum()` methods on Iterators. I think orphan rules could allow that we implement this for `Option<Array<T, D>>` (or potentially for `Result` of the same, a different design).

If we can't use the iterator method, we can design a more appropriate ndarray focused API that supports our use case. When we write generic algorithmic devices in ndarray we've preferred to not make them specific to any arithmetic operation, just to have more flexibility, so that could for example be done.

But if I have a go at that design - it ends up looking a lot like fold? Define a neutral element and a fold function.

**Comment by rasa200** [comment]
I just checked the [itertools crate](https://crates.io/crates/itertools), specifically the [sum1](https://docs.rs/itertools/0.9.0/itertools/trait.Itertools.html#method.sum1) method (and the [product1](https://docs.rs/itertools/0.9.0/itertools/trait.Itertools.html#method.product1) method for the matter). 

They have the `std::iter::Sum<Self::Item>` trait bound:
```rust
    fn sum1<S>(mut self) -> Option<S>
        where Self: Sized,
              S: std::iter::Sum<Self::Item>,
    {
        self.next()
            .map(|first| once(first).chain(self).sum())
    }
```
but that is too restrictive: one only need to be able to apply `add` to return an option. Implementation can be with a nested match, like so:
```rust
    fn checked_sum(mut self) -> Option<Self::Item>
        where 
            Self: Sized,
            Self::Item: std::ops::Add<Self::Item, Output = Self::Item>,
    {
        self.next()
            .map(|first| self.fold(first, |acc, x| acc + x))
    }
```

# Complete self-contained example

This is what I am thinking, what do you think?
```rust
pub trait Itertools2: Iterator {
    fn checked_sum(mut self) -> Option<Self::Item>
        where 
            Self: Sized,
            Self::Item: std::ops::Add<Self::Item, Output = Self::Item>,
    {
        self.next()
            .map(|first| self.fold(first, |acc, x| acc + x))
    }
}

impl<T: ?Sized> Itertools2 for T where T: Iterator { }

#[cfg(test)]
mod tests {
	use super::*;
	use ndarray::array;

	#[test]
	fn checked_sum() {
		let a = (1..3).map(|i| array![i]); 
		let expected = Some(array![3]);
		let checked_sum = a.checked_sum();
		assert_eq!(expected, checked_sum);

		let a = (1..1).map(|i| array![i]);
		let expected = None;
		let empty_sum = a.checked_sum();
		assert_eq!(expected, empty_sum);

		let a = (0..1).map(|i| array![i]);
		let expected = Some(array![0]);
		let single_sum = a.checked_sum();
		assert_eq!(expected, single_sum);

	}
}
```

**Comment by bluss** [comment]
I think the most value is gained by supporting the existing Iterator::sum, or going with the previous fold-like solutions.

**Comment by rasa200** [comment]
I agree.

Thanks for the conversation!! 

Feel free to leave the issue open.
