### ISSUE TITLE
Parallel operations maximise CPU usage but are the same speed as non-parallel operations

### ISSUE THREAD

**Issue by chocol4te** [rust-ndarray/ndarray#813]
Apologies if this is the wrong place for this!

I am writing some fluid simulation software in Rust having ported it from some Fortran code. As I was porting it I wanted to be able to unit test with direct equality checks and so the Rust arrays needed to have the same layout as the Fortran ones. For that reason I am creating the arrays with:

```rust
let ng = 512;
let nz = 128;
Array3::<f64>::from_shape_vec((ng, ng, nz + 1).strides((1, ng, ng * ng)), data).unwrap()
```

These are typical values for the dimensions and while the ratio between them is constant they can be larger. A 2 dimensional array of width and length `ng` represents a single layer within the context of this software and `nz` defines the number of layers. Since layers need to be processed and mutated as a single unit but usually don't need access to other layers, I assumed that parallelising the software across layers would be sensible. However, I am finding that performance is not what I expect it to be despite what I assumed would be an easily parallelisable task.

I created a benchmark representative of the operations I am performing, found here:

https://github.com/chocol4te/simd_par_bench/blob/e2b492472021859e5b9ecee4d4a3fd4ffec472c6/benches/ndarray.rs

`a += b * c` (where a, b, and c are Array3's of size `ng x ng x nz`) is one of the smaller operations, some more complex operations can take many *seconds* to execute per layer but still are not significantly faster when parallelised.

The (abridged) benchmarking output on my i7-7820HQ machine is the following:
```
ndarray/muladd_zip          time:   [53.869 ms 54.170 ms 54.554 ms]

ndarray/muladd_par_zip      time:   [53.634 ms 53.747 ms 53.813 ms]

ndarray/muladd_outer        time:   [55.487 ms 55.609 ms 55.762 ms]

ndarray/muladd_par_outer    time:   [53.268 ms 53.718 ms 53.956 ms]

ndarray/muladd_par          time:   [54.283 ms 54.774 ms 55.689 ms]
```

`htop` reports 99%  and ~600% usage on the linear and parallel benchmarks respectively. 

And on a 4-socket AMD Opteron 6376 (64 cores)

```
ndarray/muladd_zip          time:   [110.70 ms 111.34 ms 112.32 ms]

ndarray/muladd_par_zip      time:   [68.002 ms 78.917 ms 94.244 ms]

ndarray/muladd_par_outer    time:   [75.164 ms 83.035 ms 95.176 ms]

ndarray/muladd_par          time:   [245.25 ms 255.72 ms 269.62 ms]
```

I read around, and the reasons I saw for this poor performance could either be:

* Inefficient memory layout, except that I've configured the strides so that this should be an optimal layout when accessing across Axis(2) and then operating linearly on Axis(0/1) 

or
* Each thread has insufficient work to do and so performance is lost to Rayon overhead, except that while `muladd_par_zip` using `par_apply` is giving (I believe) each thread a single `a += b * c` operation, `muladd_par_outer` using giving each thread a 512x512 chunk to operate on, therefore if this was the issue, then they would not have similar times.

Slightly unrelated but I am also confused that `muladd_par` using a mutex has similar performance to `muladd_par_outer` which uses `axis_iter_mut(Axis(2))`. My assumption would be that all threads constantly competing for a lock on a single shared mutex would be significantly slower than each thread getting mutable access to a single layer with no mutexes?

Any advice/suggestions are greatly appreciated, thank you! :)

**Comment by bluss** [comment]
Reduce rayon overhead by adjusting the number of threads to the number of cores (discount HT) and there's a new scheduler algorithm PR posted to the rayon repo, as another bet for something that could help. More than that, I'm interested to hear what you find out.

`(ng, ng, nz + 1).f()` should be a shorter but equivalent way to specify the array shape and layout. If C/F layout makes a difference for performance, we'd be interested.

**Comment by bluss** [comment]
I'm a bit mystified. Here are two others we can compare with.

The 1D case leaves ndarray out of the loop; the only drawback it has, that I can see, is that we don't necessarily split evenly on planes (and then the alignment of each chunk might suffer).

The split case is my most simplified version of how Zip's par_apply works, in this case spread over only two tasks.

```rust
    c.bench(
        "ndarray",
        Benchmark::new("muladd_rayon_zip_1d", |b| {
            let arr1 = gen_array();
            let mut v1 = vec![0f64; arr1.len()];
            let v2 = vec![0f64; arr1.len()];
            let v3 = vec![0f64; arr1.len()];

            b.iter(|| {
                v1.par_iter_mut().zip(&v2).zip(&v3)
                    .for_each(|((a, &b), &c)| *a += b * c);
            })
        })
        .sample_size(10),
    );


    c.bench(
        "ndarray",
        Benchmark::new("muladd_split_zip", |b| {
            let mut arr1 = gen_array();
            let arr2 = gen_array();
            let arr3 = gen_array();

            b.iter(|| {
                let f = &|a: &mut f64, b: &f64, c: &f64| *a += b * c;
                let (z1, z2) = Zip::from(black_box(&mut arr1))
                    .and(black_box(&arr2))
                    .and(black_box(&arr3))
                    .split();
                rayon::join(move || z1.apply(f), move || z2.apply(f));
            })
        })
        .sample_size(10),
    );

```

**Comment by chocol4te** [comment]
Thank you so much for your help!

Changing the layout had no effect, nor did trying alternative shapes and iterating over different axes.

Setting RAYON_NUM_THREADS to lower values was interesting, the time stayed exactly the same but CPU usage dropped to around 300% on 4 threads and 150% on 2 threads.

`muladd_rayon_zip_1d` reports the same 54ms that all the other benchmarks did, `ndarray/muladd_split_zip` is reporting 46ms so a 15% improvement!

I added two other benchmarks as a sanity check using `Vec<f64>`s.

```
c.bench(
        "ndarray",
        Benchmark::new("muladd_vec", |b| {
            let mut rng = XorShiftRng::from_entropy();

            let mut arr1 = Vec::<f64>::with_capacity(NG * NG * (NZ + 1));
            let mut arr2 = Vec::<f64>::with_capacity(NG * NG * (NZ + 1));
            let mut arr3 = Vec::<f64>::with_capacity(NG * NG * (NZ + 1));

            for _ in 0..NG * NG * (NZ + 1) {
                arr1.push(rng.gen());
                arr2.push(rng.gen());
                arr3.push(rng.gen());
            }

            b.iter(|| {
                arr1.iter_mut()
                    .zip(arr2.iter())
                    .zip(arr3.iter())
                    .for_each(|((a, b), c)| *a += b * c)
            })
        })
        .sample_size(10),
    );

    c.bench(
        "ndarray",
        Benchmark::new("muladd_vec_par", |b| {
            let mut rng = XorShiftRng::from_entropy();

            let mut arr1 = Vec::<f64>::with_capacity(NG * NG * (NZ + 1));
            let mut arr2 = Vec::<f64>::with_capacity(NG * NG * (NZ + 1));
            let mut arr3 = Vec::<f64>::with_capacity(NG * NG * (NZ + 1));

            for _ in 0..NG * NG * (NZ + 1) {
                arr1.push(rng.gen());
                arr2.push(rng.gen());
                arr3.push(rng.gen());
            }

            b.iter(|| {
                arr1.par_iter_mut()
                    .zip(arr2.par_iter())
                    .zip(arr3.par_iter())
                    .for_each(|((a, b), c)| *a += b * c)
            })
        })
        .sample_size(10),
    );
```

`muladd_vec` takes the same 54ms, `muladd_vec_par` takes 45ms so close to `muladd_split_zip`.

I'm running the `ndarray` benchmarking suite now to see what it reports for the parallel operations.

**Comment by bluss** [comment]
The split benchmark can be a model for how rayon's parallel iterators work for ndarray. We supply a splitting function in the parallel iterator implementation (for Zip); rayon will split the work as many times as it thinks is feasible. Each Zip chunk runs as a job in the thread pool.

Note that while the closure in par_apply is elementwise, the final chunk size is probably (hopefully!) much larger than a single element.

If the split benchmark doesn't give a 50% speedup, something is wrong or the problem is too small? But 50 ms is not a short time.

The comparison to 1D Vec could be useful, because it will use rayon's indexed zip/splitting strategy and ndarray's parallel Zip will use rayon's unindexed splitting strategy.

The only synchronization I can think of slowing this down would be rayon's folder's "full" flag which should stop the iterator if it has early exit (like find, or try_fold); if it's not optimized out for iterators that don't have early exit, then it could be a problem.

**Comment by chocol4te** [comment]
Oh I didn’t realise it was chunked automatically!

Well since it’s unlikely to be an issue with ndarray, should I just close this issue but add a comment when/if I fix it just in case someone else has the same problem?

Sorry for troubling you

**Comment by bluss** [comment]
Let's ponder the basics, your array is 512 x 512 x 129 and that's roughly 256 MB of data. It doesn't fit in any CPU cache, and addition is very fast, so the bottleneck should be speed of memory to cache. You need an operation that is more CPU intensive to better make use of the CPU? Hence the .exp() invocations in the benchmarks, or why benchmarkers love matrix mulitiplication so much - it has a good ratio of number of operations to the amount of data it needs.

**Comment by bluss** [comment]
But, I think with better vectorization, it would be more efficient at moving memory. You could try using `RUSTFLAGS=-Ctarget-cpu=native` to see if it will autovectorize better for you.

**Comment by chocol4te** [comment]
Ah okay, that makes a lot more sense, I'll try what you suggested. Thank you!
