### ISSUE TITLE
Shouldn't ArrayView::view() expand the lifetime instead of creating a new one?

### ISSUE THREAD

**Issue by pkubik** [rust-ndarray/ndarray#816]
Not sure if it's a desired behavior or a bug, so please correct me if I'm wrong.

Right now calling calling `view` on an `ArrayView` leads to a creation of an `ArrayView` with a new lifetime. I believe that since it's still pointing to the same underlying data it should rather maintain the lifetime of the `self`.

E.g. following function fails, because the lifetime of the `ArrayView` returned by `ar.view()` is limited to the lifetime of the parameter variable:
```
fn crop<'a>(ar: ArrayView2<'a, f32>) -> ArrayView2<'a, f32> {
    ar.view()
}
```

```
error[E0515]: cannot return value referencing function parameter `ar`
  --> src\basic_types.rs:31:5
   |
31 |     ar.view()
   |     --^^^^^^^
   |     |
   |     returns a value referencing data owned by the current function
   |     `ar` is borrowed here
```

The following snippet works:

```
fn crop<'o, 'a>(ar: &'o ArrayView1<'a, f32>) -> ArrayView1<'o, f32> {
    ar.view()
}
```

What's dictating such behavior?

**Comment by bluss** [comment]
See .view()'s definition as a method defined on ArrayBase. That's determining this.

The first function can be rewritten to just have `ar` in the body and it will compile (ArrayView2 is Copy).

**Comment by pkubik** [comment]
@bluss My problem is that there are other functions that call `view` in their bodies. In my case I wanted to use `slice`:
```
    pub fn slice(&self, indexes: &D::SliceArg) -> ArrayView<A, D> {
        let mut arr = self.view();
        arr.islice(indexes);
        arr
    }
```

**Comment by pkubik** [comment]
A semi-practical example of what I'd like to do:
```
use ndarray::*; // 0.13.0

fn compute_roi(img: &Array2<f32>, crop_more: bool) -> ArrayView2<f32> {
    let crop1 = img.slice(s![1..-1, 1..-1]);
    
    if crop_more {
        crop1.slice(s![1..-1, 1..-1])
    } else {
        crop1   
    }
}

pub fn main() {
    let img = array![[1.0f32, 2.0, 3.0], [1.0, 2.0, 3.0]];
    let _roi = compute_roi(&img, true);
}
```
https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=43b0fcae9b56c9d5bb6992567d720efb

**Comment by bluss** [comment]
slice_move seems good for this

**Comment by pkubik** [comment]
That's true. Now I see that it's a common pattern that each function `<fun>` calls `<fun>_move` I guess should always use the latter if I want to act on an ArrayView. Actually, what would be a reason to not use `<fun>_move` version on an ArrayView?

**Comment by bluss** [comment]
if you just want a new temporary view, then regular slice is a good default. The most general array view is not copyable (IxDyn is not Copy)

**Comment by pkubik** [comment]
Thanks. I would never come up with using `_move` suffix in this case myself. I think I can use to solve most of my issues so far.

Yet I'm still puzzled why `view()` cannot behave the way I described. Would it be impossible / difficult to implement in Rust? Right now `view` is implemented for very generic `ArrayBase` so it's obviously not possible to preserve the original lifetime - the data lifetime exists only if it's an `ArrayView` (or `ArrayViewMut`, etc.). I guess there would have to be some additional `Viewable` trait that `Array` and `ArrayView`s would implement differently.

I'm just really curious why it's not the case, because it seems like it would erase a lot of confusion.

**Comment by bluss** [comment]
Maybe it can be solved, but making it depend on storage type and being different between & and &mut views is not my favourite thing either. The big picture thing we need to achieve is to lose the ArrayBase (I hope it's possible) focus and move the main interface to traits, not inherent methods

**Comment by pkubik** [comment]
Looks promising. I don't understand all details of the implementation but I don't think it's the right place to continue this topic. This seems like a breaking change. Is there any kind of roadmap it's currently on?

**Comment by bluss** [comment]
It's not an important issue at the moment. Feel free to rewrite this issue into a feature request?

**Comment by pkubik** [comment]
I'll pass. The workaround for using `slice_move` is sufficient for now. There is no reason to drive such invasive change if it's going to be eventually replaced with something seemingly better in the future.
