### ISSUE TITLE
Getter for dim in Shape

### ISSUE THREAD

**Issue by RolfStierle** [rust-ndarray/ndarray#820]
For `Shape`, there is not getter for the dimension stored inside the structure. There was one, but now it is solely a comment (see below): 
```rust
impl<D> Shape<D>
where
    D: Dimension,
{
    // Return a reference to the dimension
    //pub fn dimension(&self) -> &D { &self.dim }
    /// Return the size of the shape in number of elements
    pub fn size(&self) -> usize {
        self.dim.size()
    }
}
```
Is there a possibility to extract the exact dimension stored inside `Shape` to use it to modify the dimensions of struct definitions (minimal example below) outside of the crate? 

```rust
struct Tester<D: Dimension> {
    weight: Array<f64, D::Larger>,
}

impl Tester<Ix1> {
    fn new<Sh>(shape: Sh, first_dim: usize) -> Self
    where
        Sh: ShapeBuilder<Dim = Ix1>,
    {
        let dim_in = shape.into_shape().dim;  // This is not possible because the field `dim` is private. How can one obtain the dimension?
        let shape_new = Shape::from(Ix2(first_dim, dim[0]));
        let weight = Array::<f64, Ix2>::zeros(new);
        // ... modify `weight` ...
        Self { weight }
    }
}
```

**Comment by bluss** [comment]
Makes sense. Some redesign is needed. Right now, these are only designed for argument conversion for the constructors, and are not intended to be modified like this.

**Comment by RolfStierle** [comment]
Thank you for you reply.

**Comment by stokhos** [comment]
Is anyone working on this.  If not I'd like to work on this issue. @bluss @jturner314

**Comment by bluss** [comment]
Feel free to add this accessor in a simple way. Shape/StrideShape needs redesign but I'd like to give input on that another time
