### ISSUE TITLE
API to create an ArrayView backed by a slice

### ISSUE THREAD

**Issue by nagisa** [rust-ndarray/ndarray#825]
I have a slice of data `&[u8]` which I would like to "interpret" as a multidimensional array view for convenience purposes. There doesn’t appear to exist an API that can do that, however – you can only convert owned `Vec`tors to owned arrays.

**Comment by mulimoen** [comment]
I think you are looking for [`from_shape` for `ArrayView`](https://docs.rs/ndarray/0.13.1/ndarray/type.ArrayView.html#method.from_shape).
