### ISSUE TITLE
Help with R language integration

### ISSUE THREAD

**Issue by andy-thomason** [rust-ndarray/ndarray#830]
I am publishing a package for extending the R language in Rust

https://github.com/extendr

It would be very nice to get some advice or more tangible help wrapping the R vector and
matrix objects in ndarray wrappers.

R matrices are fortran order (column major) indexed as [row, column]
allocation is managed by the R library (libR) generating an object that
we manage through the R internals API.

Two options should be available.

A view wrapper (ViewRepr) to wrap a input array object, hopefully outliving the underlying R object.
An owner object (OwnedRepr) that wraps an R array object.

Any pointers and examples of wrapping external objects would be helpful.

**Comment by bluss** [comment]
ndarray does not at the moment support creating custom owned arrays like that unfortunately, but using array views is possible.

**Comment by andy-thomason** [comment]
No worries. I'll provide an ArrayView wrapper, this should be enough.

**Comment by andy-thomason** [comment]
Thanks for the help.
