### ISSUE TITLE
Cannot use some binary operators "foo_assign" on &mut ArrayBase

### ISSUE THREAD

**Issue by Ionizing** [rust-ndarray/ndarray#833]
Thank you for your outstanding work on `ndarray` which helped me a lot on my project. But I came across some issues on array's element wise operations:

Consider the [MWE](https://play.rust-lang.org/?version=stable&mode=debug&edition=2018&gist=334b015c3aa77a22f26eab60db5ee43d) in the following:

```rust
use ndarray::{Array1, arr1};

// fn cannot_compile(mat_a: &mut Array1<u32>, mat_b: &Array1<u32>) {
//     mat_a += mat_b;
// }

fn can_compile(mat_a: &mut Array1<u32>, mat_b: &Array1<u32>) {
    let mut view_a = mat_a.view_mut();
    let view_b = mat_b.view();
    
    view_a += &view_b;
}

fn can_compile_but_takes_ownership(mut mat_a: Array1<u32>, 
                                       mat_b: &Array1<u32>)
                                            -> Array1<u32> {
    mat_a += mat_b;
    mat_a
}

fn main() {
    let mut mat_a = arr1(&[1u32, 2, 3]);
    let mat_b = arr1(&[4u32, 5, 6]);
    
    can_compile(&mut mat_a, &mat_b);
    assert_eq!(&mat_a, &arr1(&[5u32, 7, 9]));
    
    assert_eq!(can_compile_but_takes_ownership(mat_a, &mat_b), arr1(&[5u32, 7, 9]));
    
    // cannot_compile(&mut mat_a, &mat_b);  // cannot compile
    // assert_eq!(&mat_a, &arr1(&[5u32, 7, 9]));
}
```

When uncommenting the `cannot_compile` blocks, we will get the error 
```
  |
4 |     mat_a += mat_b;
  |     -----^^^^^^^^^
  |     |
  |     cannot use `+=` on type `&mut ndarray::ArrayBase<ndarray::data_repr::OwnedRepr<u32>, ndarray::dimension::dim::Dim<[usize; 1]>>`
```

I can manage to do the job using `ArrayView` or taking the ownership, but, it's somewhat 'inelegant'. Would it be possible that some patches will be added to make the uncommented blocks compile?

**Comment by jturner314** [comment]
While I do believe the arithmetic operations need to be generalized to more combinations of types, in this particular case, the current behavior is sensible. For example, it matches the behavior of `u32`:

```rust
fn foo(a: &mut u32, b: u32) {
    // a += b; // doesn't compile: binary assignment operation `+=` cannot be applied to type `&mut u32`
    *a += b; // does compile
}
```

```rust
fn foo(mat_a: &mut Array1<u32>, mat_b: &Array1<u32>) {
    // mat_a += mat_b; // doesn't compile
    *mat_a += mat_b; // does compile
}
```

Are you satisfied with the solution of using a `*` (as shown above)?

**Comment by Ionizing** [comment]
Sure, thank you very much ! It seems I should review the TRPL again :-) .

By the way, could you please update the dependency `num-complex` to "0.3", which could avoid conflicts with some other crates like this:
<img width="851" alt="image" src="https://user-images.githubusercontent.com/17506747/86932162-909b9c00-c16b-11ea-920a-ccc4673c585e.png">

**Comment by bluss** [comment]
You are right, making a new release and updating num-complex should be a priority

**Comment by Ionizing** [comment]
Okay, I appreciate your work~
