### ISSUE TITLE
Impossible to use s! with #![forbid(unsafe_code)]

### ISSUE THREAD

**Issue by im-0** [rust-ndarray/ndarray#838]
https://github.com/rust-ndarray/ndarray/pull/404 seems not working anymore. I'm getting following error:

```
error[E0453]: allow(unsafe_code) overruled by outer forbid(unsafe_code)
   --> src/img.rs:153:27
    |
153 |     let mask = mask.slice(ndarray::s![upper..=lower, ..]);
    |                           ^^^^^^^^^^^^^^^^^^^^^^^^^^^^^^ overruled by previous forbid
    | 
   ::: src/main.rs:4:11
    |
4   | #![forbid(unsafe_code)]
    |           ----------- `forbid` level set here
    |
    = note: this error originates in a macro (in Nightly builds, run with -Z macro-backtrace for more info)
```

* rustc 1.45.2
* ndarray 0.13.1

**Comment by jturner314** [comment]
The `s!` macro expands to unsafe code but has an `#[allow(unsafe_code)]` annotation. This works with `#[deny(unsafe_code)]` (which respects the `allow` annotation) but not `#[forbid(unsafe_code)]` (which overrules the `allow` annotation). In other words, you just need to change your `#![forbid(unsafe_code)]` to `#![deny(unsafe_code)]`. [See the docs for more info.](https://doc.rust-lang.org/reference/attributes/diagnostics.html#lint-check-attributes)

**Comment by im-0** [comment]
Ah, I somehow forgot that "deny" and "forbid" are different, and that I use the latter. Thanks a lot!
