### ISSUE TITLE
Is it possible to index an N-dimensional ArrayBase using a single offset into the slice?

### ISSUE THREAD

**Issue by bonsairobo** [rust-ndarray/ndarray#841]
I know there is a `to_slice` method that could make this work, but it returns `Option`. I'm wondering if I can index, for example, a 3D `ArrayBase`, using just one number, assuming I know the memory layout (row-major). In certain applications, it is too expensive to do the multiplications to convert NdIndex into an offset for every point.

**Comment by bluss** [comment]
If you know the array is row major, then you can use as_slice and index into the resulting slice. Still, multidimensional or single dimensional indexing is not recommended for processing in a loop - rather use the traversal methods mentioned in the docs.

The raw access is through the raw pointer accessors - pointers which you can offset manually as you said - as briefly mentioned in the as_ptr doc, but this is not easy to use.
