### ISSUE TITLE
Support use case: Memoizing NDArray

### ISSUE THREAD

**Issue by hypercubestart** [rust-ndarray/ndarray#846]
Hi all!

I have a use case for NDArray, where I would like to store memoized NDArrays into a map, and update the map with either a "owned arrays" (with its own data) or some view/reference to an already owned array in the map (something like ArrayView or ArcArray). All the solutions I can think of require **always copying the data, which I do not want.** 

![image](https://user-images.githubusercontent.com/24601452/97528188-55b3b300-196a-11eb-927c-a40e819ce2f5.png)
this is what I want, but the code above doesn't work due to lifetimes...

Does NDArray support this use case?

**Comment by bluss** [comment]
This issue needs a more clear description of what is needed from ndarray.

**Comment by hypercubestart** [comment]
hi @bluss ! I am using ndarray in my program, which creates a computation graph where each node returns an ndarray. To evaluate the graph, I was originally using a naive traversal which returned an owned ndarray from each node, but this was too slow because of copying, and many operations do not change the underlying data and only the view layout.

Thus, I want to memoize my computation, and store within my map owned ndarrays and view ndarrays (which will reference owned ndarrays) in the map. I wasn't able to get around Rust lifetimes though with prevented mutating the map while preserving references (as it should not allow), and since I thought this may be a fairly common use case I was wondering whether there is any solutions in the community

**Comment by xd009642** [comment]
@hypercubestart you could potentially use [RefCell](https://doc.rust-lang.org/std/cell/struct.RefCell.html) from the sounds of it, you'd need to be careful not to do anything invalid like multiple mutable accesses of the same asset the same time. But if your design prevents that already or you use a mutex it should be fine

**Comment by hypercubestart** [comment]
> @hypercubestart you could potentially use [RefCell](https://doc.rust-lang.org/std/cell/struct.RefCell.html) from the sounds of it, you'd need to be careful not to do anything invalid like multiple mutable accesses of the same asset the same time. But if your design prevents that already or you use a mutex it should be fine

Hi @xd009642 , I've tried wrapping the CowArray with RefCell like `HashMap<i32, RefCell<CowArray<i32, IxDyn>>>`, which ran into the same errors with lifetimes. The problem is that the CowArray lifetime is the same as the lifetime as the mutable borrow of HashMap so the second mutable borrow  in the for loop of main is invalid.

Can you elaborate on the mutex part?
Thanks!

**Comment by xd009642** [comment]
oh I see, hmmm. And the mutex part was to prevent multiple mutable borrows if it was a risk to avoid the panic.

What if you used two data structures, say the hashmap, and then another one that's guaranteed to provide a consistent ID like a Slab. Then your hashmap is just `HashMap<i32, usize>` (usize because when you insert into slab the id type is usize). You can then have multiple IDs in the map and just a single owned array in the slab

**Comment by hypercubestart** [comment]
@xd009642 I've considered something similar to that idea, but my use case requires me to be able to edit the view of the underlying data, so while the data itself remains constant I need to change the view of the data (like the ArrayView/CowArray view variant of NDArray). I'm stuck here since I'm not sure how to do this

**Comment by bluss** [comment]
I suggest using the rust users forum to figure out how to implement it and then come back to make a feature request to ndarray. Thanks
