### ISSUE TITLE
Incompatible with serde_reflection

### ISSUE THREAD

**Issue by jzrake** [rust-ndarray/ndarray#873]
I would like to serialize `ndarray` objects to binary and open them as numpy arrays in Python. The `serde_reflection` crate enables discovery of the format of `Serialize` data structures, so the struct description can be written to meta-data and used from other languages. However the serde reflection crate induces a panic in the `ArrayVisitor` struct. Reproducer is below:

```Rust
use serde_reflection::{Tracer, TracerConfig, Samples};
let mut tracer = Tracer::new(TracerConfig::default());
let samples = Samples::new();
tracer.trace_type::<ndarray::Array1<i32>>(&samples).unwrap();
```

**Comment by bluss** [comment]
This is the panic message

```rust
     Running `target/debug/testcase`
Hello, world!
thread 'main' panicked at 'called `Result::unwrap()` on an `Err` value: Custom("Failed to deserialize value: \"unknown array version: 0\"")', src/main.rs:10:53
stack backtrace:
   0: rust_begin_unwind
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/std/src/panicking.rs:483
   1: core::panicking::panic_fmt
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/panicking.rs:85
   2: core::option::expect_none_failed
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/option.rs:1234
   3: core::result::Result<T,E>::unwrap
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/result.rs:973
   4: testcase::main
             at ./src/main.rs:10
   5: core::ops::function::FnOnce::call_once
             at /rustc/7eac88abb2e57e752f3302f02be5f3ce3d7adfb4/library/core/src/ops/function.rs:227
note: Some details are omitted, run with `RUST_BACKTRACE=full` for a verbose backtrace.
```

I would guess serde-reflection has some guidance on what a serde impl has to do to work with their protocol, so we need to turn to their docs.

**Comment by jzrake** [comment]
I'd like to help, however I realized there is a far simpler solution to getting binary data from Rust into Python: the serde_pickle crate. It makes me wonder what people wrote the Bincode adapter Python adapter code for.

I am going to close this issue since it probably does not affect anyone else.

**Comment by bluss** [comment]
To solve the serde reflection issue, look at point (2) under https://github.com/novifinancial/serde-reflection/tree/master/serde-reflection#coverage-guarantees

**Comment by jzrake** [comment]
Thanks for pointing that out. It seems this is not a bug in ndarray's serde impl, but a detail about how to use serde_reflection; you need to provide some dummy data via `trace_value` since ndarray does validation.

**Comment by jturner314** [comment]
@jzrake The [`ndarray-npy`](https://crates.io/crates/ndarray-npy) crate may be of interest. It provides support for writing/reading `.npy` and `.npz` files (the formats used by `numpy.load` and `numpy.save/savez/savez_compressed`) for arrays of primitive types (integers/floats/bools).
