### ISSUE TITLE
as_slice vs to_slice?

### ISSUE THREAD

**Issue by OliverEvans96** [rust-ndarray/ndarray#897]
Hello!

It looks like [`ArrayBase::as_slice`](https://docs.rs/ndarray/0.14.0/ndarray/struct.ArrayBase.html#method.as_slice) and [~`ArrayBase`~`ArrayView::to_slice`](https://docs.rs/ndarray/0.14.0/ndarray/type.ArrayView.html#method.to_slice) are basically identical.

`as_slice`:
```rust
/// Return the array’s data as a slice, if it is contiguous and in standard order.
/// Return `None` otherwise.
///
/// If this function returns `Some(_)`, then the element order in the slice
/// corresponds to the logical order of the array’s elements.
pub fn as_slice(&self) -> Option<&[A]>
where
    S: Data,
{
    if self.is_standard_layout() {
        unsafe { Some(slice::from_raw_parts(self.ptr.as_ptr(), self.len())) }
    } else {
        None
    }
}
```

`to_slice`:
```rust
/// Return the array’s data as a slice, if it is contiguous and in standard order.
/// Return `None` otherwise.
pub fn to_slice(&self) -> Option<&'a [A]> {
    if self.is_standard_layout() {
        unsafe { Some(slice::from_raw_parts(self.ptr.as_ptr(), self.len())) }
    } else {
        None
    }
}
```

I was just wondering if there's a difference between them. If not, perhaps one should be removed in favor of the other.

Thanks!
Oliver

**Comment by OliverEvans96** [comment]
Ah, I see now that `to_slice` is for `ArrayView`, not `ArrayBase`. I'm still curious about the slight variations in name and implementation if anyone would be so kind as to explain.

**Comment by bluss** [comment]
New version will have improved docs https://github.com/rust-ndarray/ndarray/commit/e071bdbe363ac8fed6a573e3eafcc34e22ab2d07
