### ISSUE TITLE
Make `AxisDescription` a non-tuple-struct

### ISSUE THREAD

**Issue by jturner314** [rust-ndarray/ndarray#914]
I'm curious why [`AxisDescription` is a tuple struct](https://docs.rs/ndarray/0.14.0/ndarray/struct.AxisDescription.html). Since the fields are `pub` anyway, I think it would be more convenient to change the definition to this

```rust
pub struct AxisDescription {
    pub axis: Axis,
    pub len: usize,
    pub stride: isize,
}
```

and remove the `.axis()`, `.len()`, and `.stride()` methods.

**Comment by bluss** [comment]
Sure and the methods can be deprecated first (there is _no_ field-method name conflict)
