### ISSUE TITLE
Enable accessing subviews via indices and full ranges

### ISSUE THREAD

**Issue by thecooldrop** [rust-ndarray/ndarray#933]
Hello maintainers,

here I have a proposal for a feature which may increase the ergonomics of how we use ndarray. Hear me out.

Right now if I want to access n-th subview of a 3D matrix then I have to do something like:

```rust
let mut example = arr3([[[1,1,1,1], [1,1,1,1]],
                               [[2,2,2,2], [2,2,2,2]],
                               [[3,3,3,3], [3,3,3,3]]]);
// to acces the first matrix I have to do
example.index_axis(Axis(0), 0);
// to assign to first matrix I have to do
example.index_axis_mut(Axis(0), 0).assign(&someOtherMatrix); 
```

What I would like to be able to do is:

```rust
let mut example = arr3([[[1,1,1,1], [1,1,1,1]],
                               [[2,2,2,2], [2,2,2,2]],
                               [[3,3,3,3], [3,3,3,3]]]);
// Access the first matrix
example[0, .., ..] 

// Assign to first matrix
example[0, .. , ..] = someOtherMatrix;
```

In my opinion this would give a better feel that we are actually working with n-dimensional data. I have a feeling that this idea is simply, but I do not know if internals of ndarray would allow this. Please discuss.

Edit: Naturally I would not wish this to be applicable only along first axis, but along any arbitrary axis. The example above is just an example and not complete specification

**Comment by bluss** [comment]
We would support that syntax if Rust had features that allowed it. Rust doesn't support it - but it would be cool if these kinds of issues - what features Rust would need to support ndarray-like use cases better - would be brought up on the internals forum.

**Comment by jturner314** [comment]
As @bluss mentioned, this is not currently possible, although the existing [`slice`](https://docs.rs/ndarray/0.14.0/ndarray/struct.ArrayBase.html#method.slice) and [`slice_mut`](https://docs.rs/ndarray/0.14.0/ndarray/struct.ArrayBase.html#method.slice_mut) methods may be closer to what you're looking for:

```rust
// Access the first matrix
example.slice(s![0, .., ..])

// Assign to first matrix
example.slice_mut(s![0, .., ..]).assign(&someOtherMatrix)
```
