### ISSUE TITLE
Compilation error E0277 on windows 10

### ISSUE THREAD

**Issue by Kaduo** [rust-ndarray/ndarray#954]
Trying to build ndarray 0.15 on Windows 10 yields a long list of E0277 errors, here is the last one for instance:

![image](https://user-images.githubusercontent.com/2149558/112717984-5a1bd200-8ef0-11eb-8de5-662f27b6ddcf.png)

They all seem to concern the unsafe "DataOwned: Data" trait. Version 0.14.0 builds just fine.

**Comment by bluss** [comment]
What's your rustc version?

**Comment by Kaduo** [comment]
Thank you, I was using an older version by mistake. Everything works fine now that I updated my toolchain. Sorry for the bother!
