### ISSUE TITLE
Make ArrayView(Mut)'s parallel iterators implement IndexedParallelIterator

### ISSUE THREAD

**Issue by cassiersg** [rust-ndarray/ndarray#964]
Axis iterators can be used as IndexedParallelIterator, but it is not the case for ArrayBase, as shown below:
```rust
use rayon::prelude::*;
fn main() {
    let a = ndarray::Array1::<u32>::zeros(5);
    test_into_par_iter(&a);
    test_into_par_iter_indexed(&a); // <- Does not compile.
}
fn test_into_par_iter<T: IntoParallelIterator>(_x: T) {}
fn test_into_par_iter_indexed<T: IntoParallelIterator>(_x: T)
where
    T::Iter: IndexedParallelIterator,
{
}
```
From an outsider perspective, such an implementation appears to be possible. Is it intentionally omitted, or could it be added ?

**Comment by bluss** [comment]
Is the request for 1-dimensional (only possible case)?

**Comment by cassiersg** [comment]
It isn't obvious to me that 1-dimensional is the only possible case.

I think that in any case, documenting explicitly that (or in which case) IndexedParallelIterator is not implemented would be a nice addition.

**Comment by bluss** [comment]
What about the existing docs in the parallel module? Propose an update

**Comment by cassiersg** [comment]
I apparently managed to completely miss the existence of the docs (and existence) of the parallel module, which are actually great. I suggest (#971) to add a link where the rayon feature is described since that was my entry point for this feature.
