### ISSUE TITLE
Potentially support rkyv

### ISSUE THREAD

**Issue by stokhos** [rust-ndarray/ndarray#976]
[rkyv](https://github.com/djkoloski/rkyv) which claims to be faster than serde.

Maybe its a good idea to replace serde with rkyv?

**Comment by xd009642** [comment]
So serde is part of the public API with the serde feature enabled to allow users using serde to integrate ndarray into their code. Removing serde and replacing with rkyv would then force users to rewrite existing serde code they have to use rkyv or not upgrade their ndarray version. So removing serde isn't really a viable solution.

However, there could potentially be a rkyv feature as well as a serde feature for rkyv users.

**Comment by bluss** [comment]
rkyv is quickly making breaking releases. Since it would be a public dependency, we have higher standards. Let it settle a bit I think

**Comment by bluss** [comment]
I'll close this for now. There's a big set of possible features, and we've already decided rkyv is not an option *right now*. Also, there is no use case proposed for this feature.

**Comment by AlexDaniel** [comment]
Just tried to save an ndarray with rkyv and out of the box it doesn't work. The development of rkyv seems to have slowed down a bit, maybe it is time to support it now?
