### ISSUE TITLE
Zipping ExactChunks and producer dimension mismatch

### ISSUE THREAD

**Issue by frjnn** [rust-ndarray/ndarray#993]
Currently it is not possible to zip  some `ExactChunks` if the chunks have been obtained from different array's axes but have the same dimensionality. I found a workaround to this that consists in calling `into_iter()` then `collect()` into a `Vec` of views and then zipping by calling `into_producer` on those `Vec`s. 

I was wondering if this was a somewhat reasonable way of doing things. Code snippet below.

```rust

let chunks1: Vec<ArrayView<f32, _>> =
            array1.exact_chunks((dim, other_dim)).into_iter().collect();

let mut chunk2: Vec<ArrayViewMut<f32, _>> = array2
            .exact_chunks_mut((another_dim, yet_another_dim))
            .into_iter()
            .collect();

ndarray::Zip::from((&chunks1).into_producer())
            .and((&mut chunks2).into_producer());
```

**Comment by jturner314** [comment]
In the example code, what are the values of the following: the shape of `array1`, the shape of `array2`, `dim`, `other_dim`, `another_dim`, and `yet_another_dim`?

**Comment by jturner314** [comment]
Does the following meet your needs? (This uses `axis_chunks_iter` and `Iterator::zip`.)

```rust
use ndarray::prelude::*;

fn main() {
    let array1 = Array4::<f32>::ones((4, 8, 5, 5));
    let array2 = Array4::<f32>::ones((6, 4, 2, 2));

    let chunks1 = array1.axis_chunks_iter(Axis(1), array1.len_of(Axis(1)) / 2);
    let chunks2 = array2.axis_chunks_iter(Axis(0), array2.len_of(Axis(0)) / 2);
    for (chunk1, chunk2) in chunks1.zip(chunks2) {
        // loop body
    }
}
```

**Comment by frjnn** [comment]
Not quite, because I need to use a `par_for_each` after.

**Comment by jturner314** [comment]
`AxisChunksIter` implements `IntoParallelIterator` (make sure to enable `ndarray`'s `rayon` feature in your `Cargo.toml`), so you can do this:

```rust
use ndarray::prelude::*;
use rayon::prelude::*;

fn main() {
    let array1 = Array4::<f32>::ones((4, 8, 5, 5));
    let array2 = Array4::<f32>::ones((6, 4, 2, 2));

    let chunks1 = array1.axis_chunks_iter(Axis(1), array1.len_of(Axis(1)) / 2);
    let chunks2 = array2.axis_chunks_iter(Axis(0), array2.len_of(Axis(0)) / 2);
    chunks1
        .into_par_iter()
        .zip(chunks2)
        .for_each(|(chunk1, chunk2)| {
            // loop body
        });
}
```

**Comment by frjnn** [comment]
> [`AxisChunksIter`](https://docs.rs/ndarray/0.15.1/ndarray/iter/struct.AxisChunksIter.html) implements [`IntoParallelIterator`](https://docs.rs/rayon/1.5.0/rayon/iter/trait.IntoParallelIterator.html) (make sure to enable `ndarray`'s `rayon` feature in your `Cargo.toml`), so you can do this:
> 
> ```rust
> use ndarray::prelude::*;
> use rayon::prelude::*;
> 
> fn main() {
>     let array1 = Array4::<f32>::ones((4, 8, 5, 5));
>     let array2 = Array4::<f32>::ones((6, 4, 2, 2));
> 
>     let chunks1 = array1.axis_chunks_iter(Axis(1), array1.len_of(Axis(1)) / 2);
>     let chunks2 = array2.axis_chunks_iter(Axis(0), array2.len_of(Axis(0)) / 2);
>     chunks1
>         .into_par_iter()
>         .zip(chunks2)
>         .for_each(|(chunk1, chunk2)| {
>             // loop body
>         });
> }
> ```


Thank you very much, this was what I was looking for.
